### ISSUE TITLE
Release Includes Temporary Files

### ISSUE THREAD

**Issue by aj-foster** [ex-aws/ex_aws#1044]
Hi there 👋🏼 

This is just a quick FYI that the [latest release](https://diff.hex.pm/diff/ex_aws/2.5.2..2.5.3) appears to have a number of temporary files included. These don't appear to affect the operation of the package, but it provided a few minutes of confusion while evaluating changes.

Cheers!

**Comment by bernardd** [comment]
Ah dangit, thanks. I'm usually pretty good about avoiding those, but obviously was in a bit of a rush this time.

**Comment by aj-foster** [comment]
It happens. Thanks for all of your work!
