### ISSUE TITLE
Release v2.5.3 includes temporal files

### ISSUE THREAD

**Issue by milmazz** [ex-aws/ex_aws#1052]
### Environment

* https://diff.hex.pm

### Current behavior

While I was reviewing the diff between [ex_aws 2.5.1 → 2.5.3](https://diff.hex.pm/diff/ex_aws/2.5.1..2.5.3) before proceeding with a package update. I noticed some temporal files like: `lib/ex_aws/config/defaults.ex~`, `lib/ex_aws/operation/json.ex~`, among others.

### Expected behavior

Those temporal files with extension `.ex~` should not be included in the release artifact. Probably a _mix task_ could help to remove those files before publishing a new version in the future.

**Comment by joeybaer** [comment]
We may be able to leverage [exclude_patterns](https://hexdocs.pm/hex/Mix.Tasks.Hex.Publish.html#module-package-configuration) to prevent this as well.
