### ISSUE TITLE
S3 objects with special characters issues

### ISSUE THREAD

**Issue by azhi** [ex-aws/ex_aws#315]
AWS has [Guidelines](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) that suggest only using safe characters for object keys. However, in my use case i have to deal with at least some of the special characters in object keys. Right now i'm trying to figure out a way to do this.

Same doc suggests that client implementation should handle (escape) some of the special characters (listed in `Characters That Might Require Special Handling` section).

I wonder what's your view on these things. Do you think `ex_aws` should include escaping rules for a `Special Handling` list? Should it also force-fail upload when object key has some characters marked as `Characters to Avoid` by AWS?

UPD: after digging around the source, i've found issue #176. Doing any escaping on s3 object path leads to AWS refusing the signature, so it won't be an easy fix - need to figure out what signature AWS expects in this case. Just to clarify things: i expected the object with `+` in the key to be stored with `+`, not a space.

**Comment by up2jj** [comment]
I don't know if this is still an issue for you but I had to deal with `+` sign in key too when copying objects. After some digging I and was able to do a copy of an object  by making some workaround:

```elixir
struct = ExAws.S3.put_object_copy(@new_bucket, new_key, @old_bucket, old_key, headers)
%ExAws.Operation.S3{headers: headers} = struct
modified_key = :http_uri.encode(@old_bucket <> "/#{old_key}")
%{struct | headers: Map.put(headers, "x-amz-copy-source", modified_key)} |> ExAws.request!
```

In this case it seems that `x-amz-copy-source` needs to be properly escaped, but Elixir's `URI.encode` used in this library omits some characters (see the docs). I can submit a pull request if anybody is interested (cc: @benwilson512 )

**Comment by mikeastock** [comment]
I just opened a PR #475 that may be related to this

**Comment by benwilson512** [comment]
If this is still an issue please re-open on https://github.com/ex-aws/ex_aws_s3
