### ISSUE TITLE
Add documentation for getting URLs of uploaded files

### ISSUE THREAD

**Issue by adsteel** [ex-aws/ex_aws#364]
I apologize if this is obvious, but I've been struggling with how to do this and none of my workarounds seem to be working.

When I upload a file using `put_object`, I don't see a URL returned. How do I retrieve that object?

The output of `S3.put_object` is:

```elixir
{:ok, %{body: "", headers: [{"x-amz-id-2", "someid="}, {"x-amz-request-id", "someid"}, {"Date", "Thu, 16 Feb 2017 19:43:01 GMT"}, {"ETag", "\"sometag\""}, {"Content-Length", "0"}, {"Server", "AmazonS3"}], status_code: 200}}
```

In general, it took me a while to figure out that all of the documentation is in the code. Might be worth noting that in the Readme as well.

**Comment by benwilson512** [comment]
Hey!

I'm not sure I understand. When you use `put_object` you give it a path, and the object will be found under that path. If you want a URL someone can click on you use the `S3.presigned_url` function.

**Comment by benwilson512** [comment]
Even without the presigned url though you can just use `S3.get_object` with the exact same bucket and key to get the object. presigned_url is what you use if someone should be able to access it via a web browser or something.

**Comment by adsteel** [comment]
I definitely didn't find that method. This one? https://github.com/CargoSense/ex_aws/blob/680a01404ebfbb10a36ec9eeda82777acf60b67d/lib/ex_aws/auth.ex#L52 That would make sense for what I'm looking for.

I'm not sure what all of the arguments mean though. Could you give an example of using it?

**Comment by benwilson512** [comment]
https://hexdocs.pm/ex_aws/ExAws.S3.html#presigned_url/5

**Comment by adsteel** [comment]
Thanks. So this gives me a very long URL (with salted info):

```elixir
{:ok, url} = S3.presigned_url(s3_config(), :get, @bucket, path, [virtual_host: true])
url
=> https://my-bucket.s3.amazonaws.com/prod/attachments/1487281361/421.jpg?X-Amz-Algorithm=AWS4-BLAH-SHA256&X-Amz-Credential=AKIAIY75BLAHBA%2F20170216%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20170216T214242Z&X-Amz-Expires=3600&X-Amz-SignedHeaders=host&X-Amz-Signature=7a0cc9016d8d102blahfc5dd2a15cfablah4d3e930f013d7f4be4b
```

Other services I've used and seen return a much simpler URL that doesn't expire, but that format isn't accessible here.

https://my-bucket.s3.amazonaws.com/prod/attachments/1487281361/421.jpg

What am I missing?

**Comment by ericmj** [comment]
@adsteel Would this work?

```
"https://s3.amazonaws.com/#{bucket_used_in_put_object}/#{path_used_in_put_object}"
```

**Comment by adsteel** [comment]
Sure, that'd work great.

**Comment by adsteel** [comment]
@ericmj That's what I'm looking for, but I get an Amazon Access Denied error with that format. Maybe it has to do with how the upload POST path is configured?

**Comment by ericmj** [comment]
@adsteel Did you set `acl: :public_read` when uploading the object? By default S3 will make the file private if you don't explicitly set ACL options.

**Comment by benwilson512** [comment]
@ericmj IIRC that only works for the us-east-1 region. There could be value in having an `S3.url` function that produces a full simple URL without any of the authentication data.

@adsteel Eric's comments about permissions are dead on, unless your bucket is wide open generally you need to specify when you put the object `:public_read` if you want it publicly available.

**Comment by adsteel** [comment]
@ericmj @benwilson512 that was it. `S3.put_object(path, contents, [acl: :public_read])` got me the _ability_ to create the shortened link, but `{:ok, url} = S3.presigned_url(s3_config(), :get, @bucket, path, [virtual_host: true, acl: :public_read])` still gives me a link with lots of URL param "extras" like an expiration. I can concatenate my own simple link, but is there any `ExAws` was to generate that simple link?

**Comment by ericmj** [comment]
If your bucket is on us-east-1 you can use the string I linked above. If not you need to change "s3.amazonaws.com" to the correspoding endpoint name here http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region.

No function exists that does this for you automatically but it looks like a PR would be accepted for it.

**Comment by qilongxu** [comment]
This post might help you to set access control
[](https://medium.com/@Stephanbv/elixir-phoenix-uploading-images-to-aws-s3-with-arc-72da8049e844#.wv1ptdgwi)
