### ISSUE TITLE
S3.list_objects does not work with stream! and delimiter [patch]

### ISSUE THREAD

**Issue by ijcd** [ex-aws/ex_aws#417]
The output format of list_objects is different when a delimiter is passed. This patch allows it to work.

```
diff --git a/lib/ex_aws/s3/lazy.ex b/lib/ex_aws/s3/lazy.ex
index 72642ea..549ac63 100644
--- a/lib/ex_aws/s3/lazy.ex
+++ b/lib/ex_aws/s3/lazy.ex
@@ -13,10 +13,16 @@ defmodule ExAws.S3.Lazy do

       {fun, args} -> case fun.(args) do

-        results = %{contents: contents, is_truncated: "true"} ->
+        results = %{common_prefixes: common_prefixes = [_|_], is_truncated: "true"} ->
+          {common_prefixes, {fun, [marker: next_marker(results)]}}
+
+        %{common_prefixes: common_prefixes = [_|_]} ->
+          {common_prefixes, :quit}
+
+        results = %{contents: contents = [_|_], is_truncated: "true"} ->
           {contents, {fun, [marker: next_marker(results)]}}

-        %{contents: contents} ->
+        %{contents: contents = [_|_]} ->
           {contents, :quit}
       end
     end, &(&1))
```

**Comment by benwilson512** [comment]
Thanks! Any interest in simply submitting a PR?

**Comment by ijcd** [comment]
I didn't have tests, etc, so I started with this. I will look into that.

**Comment by ijcd** [comment]
I'm working on a PR now. I see that you use dyanmo-lite for local testing. Do you have something similar for s3?

**Comment by benwilson512** [comment]
Not at this time.

**Comment by ijcd** [comment]
Proposed fix: https://github.com/CargoSense/ex_aws/pull/453

**Comment by ijcd** [comment]
Actually, there are a few more corner cases that cause issues for stream!

When there are prefixes and objects under the same key prefix, and neither or either or both need to paginate for more results... I will add tests for that. Until I do, let's not consider this done.

**Comment by ijcd** [comment]
Updated to cover the corner cases. Take a look now.
