### ISSUE TITLE
Support AWS S3 Accelerated Transfer

### ISSUE THREAD

**Issue by evadne** [ex-aws/ex_aws#418]
[S3 Accelerated Transfer](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html) is not currently supported. One of my projects benefits greatly from having that, so we’re likely going to have it implemented either way. Is somebody else working on this for ExAWS?

I see that at a bare minimum a few things need to be changed.

1. The Operation -> HTTP Request bits need to change because one of the premises of Transfer Acceleration is that the bucket is named as a virtual host instead of a path fragment.
2. Some kind of configuration surface to expose this preference also needs to be built.
3. Some kind of documentation change will be needed.

Eh?

**Comment by benwilson512** [comment]
This looks valuable, please re-open on https://github.com/ex-aws/ex_aws_s3
