### ISSUE TITLE
HTTPotion adapter

### ISSUE THREAD

**Issue by Hinidu** [ex-aws/ex_aws#466]
Hello!
Last week I've faced the problem while trying to run many concurrent long-polling requests to SQS - the apllication consumed about 1.5 GB for 500 connections (I've tried different number of requests and it's always about 3 MB per request).
hackney pool was disabled.
At first I've replaced ExAws methods by plain hackney requests and I saw almost the same picture.
After that I've decided to try another http-client and found that HTTPotion uses only about 0.25 MB per request to do the same.
So I've built quite basic adapter to use ExAws for HTTPotion.
How do you think should something like that be included in ExAws itself? Another reason could be that if I understand correctly hackney causes a lot of different problems quite often (for example now it has the bug in its pool that leaks connections when connection timed out).
Thank you in advance!

**Comment by Hinidu** [comment]
That's my current implementation that ignores the pool and hardcodes timeout but in other regards I think it's quite good)
```elixir
defmodule ExAws.Request.HTTPotion do
  @behaviour ExAws.Request.HttpClient

  def request(method, url, body \\ "", headers \\ [], _http_opts \\ []) do
    # TODO optional
    {:ok, worker} = HTTPotion.spawn_link_worker_process(url)

    keyword_list_headers = Enum.map(
      headers, fn {header, value} -> {String.to_atom(header), value} end)

    opts =
      [
        body: body,
        headers: keyword_list_headers,
        direct: worker,
        # TODO customizable
        timeout: 30_000,
        ibrowse: [headers_as_is: true]
      ]

    case HTTPotion.request(method, url, opts) do
      %HTTPotion.Response{} = resp ->
        {:ok, resp}
      %HTTPotion.ErrorResponse{message: message} ->
        {:error, %{reason: message}}
    end
  end
end
```

**Comment by ericmj** [comment]
Do you think it would make sense to use ibrowse directly instead of using the indirection of HTTPotion. For a library like ex_aws I think it makes sense to use the more low-level library.

**Comment by Hinidu** [comment]
@ericmj Yes! Actually I forgot to mention that I was trying to use ibrowse directly but couldn't do that because I'm quite new to Elixir :disappointed: If I remember correctly there were some issues with conversion from string to char lists or something like that.

**Comment by ericmj** [comment]
> If I remember correctly there were some issues with conversion from string to char lists or something like that.

ex_aws could do those conversions if that's the case.

What worries me is code like this `String.to_atom(header)`, this is unnecessary and if it is HTTPotion that require atom conversion we should not use it.

**Comment by Hinidu** [comment]
> What worries me is code like this String.to_atom(header), this is unnecessary and if it is HTTPotion that require atom conversion we should not use it.

Yes, of course I've tried at first send headers as is but `HTTPotion` expects keyword lists.

**Comment by benwilson512** [comment]
@Hinidu Did you try using `:hackney` with the pool disabled?

**Comment by Hinidu** [comment]
@benwilson512 Yes, I told that in my original message :-)
> hackney pool was disabled.

**Comment by Hinidu** [comment]
By the way I don't think that disabling the pool can reduce the amount of memory consumed per request.

**Comment by benwilson512** [comment]
Well the idea with disabling the pool is that while individual requests may use a certain amount of memory that memory is quickly reclaimed with the connection process is completed.

Setting aside hackney for a moment, I have two main concerns with your current implementation: `String.to_atom` and start_linking a worker.

The first thing Eric already covered and in looking at the `ibrowse` code can be handled just by calling `ibrowse` directly. The second thing though I'm just not sure I understand. What's the point in starting a starting the process explicitly here?

**Comment by Hinidu** [comment]
> The second thing though I'm just not sure I understand. What's the point in starting a starting the process explicitly here?

It was the simplest (and maybe the only?) way to ignore ibrowse pool. You can create a worker and send request using it. Without that your request will go through the pool.
Maybe it's worth to note that ibrowse handle separate pools for each pair `host:port`.

**Comment by benwilson512** [comment]
@ericmj is reminding me that the main issue with `ibrowse` is that it doesn't do hostname verification, which significantly undercuts the security of connecting to HTTPS websites. https://blog.voltone.net/post/7 covers in more detail what needs to be configured in order for ibrowse to handle this. I'm curious how much that affects the memory differential.

As an aside, 500 concurrent connections is a lot, what's the use case?

**Comment by Hinidu** [comment]
> Well the idea with disabling the pool is that while individual requests may use a certain amount of memory that memory is quickly reclaimed with the connection process is completed.

Actually in my use case connection pool is not very useful. I need one long polling 20s request to SQS for each online user and shortly after the getting of response for some user I will make another request for him. So I don't need limiting behavior of the pool, but with the big enough pool connection speed up I could gain would be useful I think.

**Comment by Hinidu** [comment]
> @ericmj is reminding me that the main issue with ibrowse is that it doesn't do hostname verification, which significantly undercuts the security of connecting to HTTPS websites. https://blog.voltone.net/post/7 covers in more detail what needs to be configured in order for ibrowse to handle this. I'm curious how much that affects the memory differential.

Thank you for the link, I will read it.

> As an aside, 500 concurrent connections is a lot, what's the use case?

I'm writing the frontend for the backend game services. I want to spin up multiple instances of frontend depending on the load. Different backend services want to send some message to the user from time to time. My current idea is to avoid looking what frontend specific user is connected to (especially because it can reconnect to another one) and sending such messages to the specific for the client queue in SQS. So each frontend should poll messages in a queue for each connected client.

**Comment by Hinidu** [comment]
@benwilson512 I've read the blog you've pointed out. I will try to check tomorrow the workarounds provided in this article and measure how they affect the memory consumption.

**Comment by Hinidu** [comment]
@benwilson512 I've tried to reproduce the steps in the article above but I can't confirm that tips provided there work stable with `HTTPotion` - it almost always returns `:ok` even if certificate is not valid, I've got only one handshake error because of hostname mismatch in a lot of trials.
Though `httpc` pass the tests. What do you think about an adapter for `httpc`? I didn't measure memory consumption yet.
Also I found in the same blog that OTP since version 19.3 has its own host verification function and it can be used instead of `ssl_verify_hostname` dependency. https://blog.voltone.net/post/11#continue

**Comment by Hinidu** [comment]
Measuring with proper certificate validation had interesting results. When I set ssl options for `httpc` to use `certifi` and `ssl_verify_hostname` it starts to consume almost as much memory as `hackney` with its default ssl options (almost 1.5 GB). Also they both consume almost 200 MB for 500 concurrent requests if I replace ssl option `cacerts` with value from `:certifi.cacerts()` by option `cacertfile` with the path to `cacert.pem` in `priv` directory (I've copied that from python's request library - just because I found it on my machine and it passes the tests from the blog post).
I still don't know why these methods give so different results.
By the way it looks not so useful to have different adapter for ExAws if I can change ssl options of hackney to get the desired result.

**Comment by Hinidu** [comment]
I have researched this behavior a little bit more and created an issue in `certifi` project https://github.com/certifi/erlang-certifi/issues/19

**Comment by benwilson512** [comment]
All in all, it seems that there is not a strong need to include an HTTPotion adapter by default.

**Comment by Hinidu** [comment]
Agree, I'm also trying to use `hackney` now, I hope that pool connection leak was fixed a few days ago and that performance issue with `cacerts` vs `cacertfile` will be resolved soon.
