### ISSUE TITLE
Renaming fields in DynamoDB item during decoding

### ISSUE THREAD

**Issue by Hinidu** [ex-aws/ex_aws#471]
Hello!
Is there a standard way of changing the name of some attribute during decoding? For example we have `pid` attribute in DynamoDB but in our struct this property is named `player_id`. We can do it during encoding by implementing `ExAws.Dynamo.Encodable` protocol but the same approach doesn't work with decoding because `ExAws.Dynamo.decode_item` convert item to a struct itself and calls our implementation of `decode` only after that.
We've implemented our own function similar to `ExAws.Dynamo.decode_item` but doing this stuff in the opposite order. And it looks like it works well but maybe there is a more standard way for doing these things?
Thank you in advance.

**Comment by benwilson512** [comment]
Hey! Please re-open on https://github.com/ex-aws/ex_aws_dynamo
