### ISSUE TITLE
AWS config seems to not work with ARN roles

### ISSUE THREAD

**Issue by bermannoah** [ex-aws/ex_aws#474]
Let me first say that it's extremely possible that I've misconfigured something... but here's the issue I'm having:

The role I can use for S3 access is not _listed_ in the config file as having the access and secret access keys, it runs through an ARN role. Our organisation has both keys - but that role is unable (for example) to create / destroy buckets. 

Is there a workaround / something I'm not doing that I need to be doing? I have configparser_ex installed.

**Comment by benwilson512** [comment]
I've now made this more clear via https://github.com/ex-aws/ex_aws/blob/master/ISSUE_TEMPLATE.md, but the ExAws issue tracker is going to focus on bugs. For help on how to use the library please use the forums, irc, or slack.
