### ISSUE TITLE
SNS MessageAttribute should be MessageAttributes

### ISSUE THREAD

**Issue by wardes** [ex-aws/ex_aws#476]
Hi, I've been trying out ExAws today, using the SMS sending feature of SNS.

I've noticed that the generated message payload sent to AWS is slightly misspelt, causing it to ignore the MessageAttributes set in the request.  For example, Amazon ignores whatever value of AWS.SNS.SMS.SenderID is sent.

Comparing the output of the HTTP request to python's Boto3 equivalent, I found that the message attributes should be spelled "MessageAttributes.entry..." not "MessageAttribute.entry...", ie, MessageAttributes is plural.

Changing the function 'build_message_attribute' in file sns.ex to read:
```
param_root = "MessageAttributes.entry.#{i + 1}" 
```
fixes the problem.

I'm not sure if this has consequences for any other parts of the API which use a similar scheme for passing through the attributes, I'm not very familiar with the codebase or the API in general.

Hope that helps! Thanks for creating ExAws.
Simon

**Comment by benwilson512** [comment]
This has been fixed, thanks!
