### ISSUE TITLE
Elasticsearch service

### ISSUE THREAD

**Issue by matrinox** [ex-aws/ex_aws#479]
I'm looking into using elixir with AWS elasticsearch. I'm currently using `tirexs` as the client. I heard that switching to AWS means replacing `tirexs` with an AWS SDK.

It's implied in issue #349 that anyone can create a module for any of the services as long as you build the current structs. We are looking into doing that and would like to eventually have it merged back into this library (so we don't have to use forks and the code can benefit from your maintenance). Any objections or considerations?

Is there anything you guys can let us know to guide us to the right path? For example, @benwilson512 mentioned something about a `RestJSON` type that he might add; I looked in the code and couldn't find it.

Is there anything you guys like for us to follow? I understand the basic structure and I read https://github.com/CargoSense/ex_aws/blob/master/CONTRIBUTING.md but the section on new stuff is "in progress."

**Comment by Hinidu** [comment]
Hey, @matrinox!
We are currently implementing Amazon GameLift support and we are waiting for response too [here](https://github.com/CargoSense/ex_aws/issues/478).
I don't know what `RestJSON` should do but it looks like you could just use `ExAws.Operation.JSON` like us or in [this PR](https://github.com/CargoSense/ex_aws/issues/478) for Amazon Polly that is also RESTful.
It's quite straightforward to add new service using existing ones as a template. For example we were using `ExAws.Dynamo` as a reference while implementing the support for GameLift.
Though I don't think that you need any support in `ex_aws` to use Elasticsearch hosted by Amazon if you don't want to do any ES infrastructure configuration from your code. I believe it's enough to provide the right URL to `tirexs` to be able to write to and search in AWS Elasticsearch.

**Comment by benwilson512** [comment]
Hey folks I apologize for the lack of feedback. The last few weeks have been a bit crazy getting the GraphQL book together, along with Elixirconf stuff. Let me see if I can get something together for these questions tonight.

**Comment by Hinidu** [comment]
No problem @benwilson512 - everybody gets busy sometimes :-) Good luck with your book!

**Comment by kerryjj** [comment]
Hi, I'll definitely be interested in seeing AWS Elasticsearch Service support. 

Tirex doesn't support signing requests with AWS Signature Version 4. The access policies on AWS Elasticsearch are also limited to Resource-based, IP-based and IAM user and role-based access policies and there's still no support to ES within a VPC. Resource and IAM/role-based permissions require signing the requests and IP-based doesn't work well if you're using something like elasticbeanstalk where the IP addresses keep changing.

So there's two options as I see it. Add request signing to Tirex, or add AWS ES support here.

**Comment by matrinox** [comment]
@kerryjj Thanks for this insight. I am still doing my research into this so I'm not sure which is better. I'm used to the Tirexs interface and think they do a decent job and update fairly regularly. I might ask if the Tirexs folks want to support AWS themselves

**Comment by kerryjj** [comment]
I found a solution that works for me in the end. Everything accessing AWS ES is coming from inside a VPC, so I can add the IP addresses of the NAT gateways to the AWS ES access policy and don't need to sign requests anymore.

**Comment by benwilson512** [comment]
Please see https://github.com/ex-aws/ex_aws/blob/master/CONTRIBUTING.md for more info on contributing.
