### ISSUE TITLE
500 response not handled due to lack of body

### ISSUE THREAD

**Issue by DavidAntaramian** [ex-aws/ex_aws#481]
I just encountered a situation where [`ExAws.Request.request_and_retry/7`](https://github.com/CargoSense/ex_aws/blob/964e6ab6acf047ab206cc6502a849c807f1d5952/lib/ex_aws/request.ex#L24) raises because the [case statement handling responses](https://github.com/CargoSense/ex_aws/blob/964e6ab6acf047ab206cc6502a849c807f1d5952/lib/ex_aws/request.ex#L38) does not account for the response that was received.

The error is:

```
(CaseClauseError) no case clause matching
```

The response given to the cases was:

```elixir
{
  :ok,
  %{
    headers: [
      {"x-amz-request-id", "REMOVED"},
      {"x-amz-id-2", "REMOVED"},
      {"Content-Type", "application/xml"},
      {"Transfer-Encoding", "chunked"},
      {"Date", "Thu, 14 Sep 2017 19:15:54 GMT"},
      {"Connection", "close"},
      {"Server", "AmazonS3"}
    ],
    status_code: 500
  }
}
```

(I have marked where possibly sensitive information was removed)

This response occurred during the AWS S3 outage on September 14, 2017.

Here, the upstream service is asking that the current connection be closed (note the header "Connection: close").  The service has not fulfilled the request, though, as indicated by the 500 status code.

The response does not have a `:body`, so it isn't caught by the [case that handles other 5xx statuses](https://github.com/CargoSense/ex_aws/blob/964e6ab6acf047ab206cc6502a849c807f1d5952/lib/ex_aws/request.ex#L47). That case would have to be enhanced to handle situations where no `:body` key is present. Retrying the request should be fine, since the HTTP client should automatically handle closing the connection (as hackney does in [`hackney_response:maybe_close/1`](https://github.com/benoitc/hackney/blob/1.9.0/src/hackney_response.erl#L325)) and opening a new one. That still leaves the question of how to formulate the `reason` for the failure. Since there is no `:body` detailing the reason, would `{:http_error, status, :connection_closed_by_remote}` be preferable?

**Comment by benwilson512** [comment]
Hey @DavidAntaramian, we ran into this too today. I think your proposed solution is a good one.

**Comment by benwilson512** [comment]
This has since been fixed.
