### ISSUE TITLE
Dynamo.decode_item returns struct with defaults if no item found

### ISSUE THREAD

**Issue by Hinidu** [ex-aws/ex_aws#488]
It looks quite strange and requires to write a little bit ugly code like this:
```elixir
    Dynamo.get_item(@inventory_table_name, key, consistent_read: true)
    |> ExAws.request!
    |> case do
      %{"Item" => item} -> {:ok, Dynamo.decode_item(item, as: Item)}
      _ -> {:error, :not_found}
    end
```
It would be great if `Dynamo.decode_item` would return `{:ok, item}` or `{:error, something}` and `Dynamo.decode_item!` would return `item` or raise an error.
What do you think about that? Maybe you have more pretty workarounds?

**Comment by Hinidu** [comment]
Another option could be an optional argument in `Dynamo.decode_item` specifying what value it should return when where is nothing to decode.

**Comment by benwilson512** [comment]
Hey! Please re-open on https://github.com/ex-aws/ex_aws_dynamo
