### ISSUE TITLE
AWS IoT support

### ISSUE THREAD

**Issue by kuffel** [ex-aws/ex_aws#489]
I wanted create a module that is calling the [AWS IoT RESTful API](http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-rest-api.html). The contributing guidelines about creating new services and new operations has no information on this. So i tried it myself:

Here is my code snippet:
```
  query = %ExAws.Operation.RestQuery{
      http_method: :get,
      path: "https://[ENDPOINT].iot.eu-west-1.amazonaws.com/things/[THINGNAME]/shadow",
      params: %{},
      body: "",
      service: :iotdata,
      action: :shadow,
      parser: &ExAws.Utils.identity/2,
    }
    ExAws.Operation.perform(query, %{
      :access_key_id => "[YOUR_KEY_HERE]",
      :secret_access_key => "[YOUR_SECRET_HERE]",
      :region => "eu-west-1"
    })
```
I am getting this error:

```
** (UndefinedFunctionError) function nil.request/5 is undefined or private
    nil.request(:get, ":https:/[ENDPOINT].iot.eu-west-1.amazonaws.com/things/[THINGNAME]/shadow", "", [{"Authorization", "AWS4-HMAC-SHA256 Credential=[YOUR_KEY_HERE]/20171001/eu-west-1/iotdata/aws4_request,SignedHeaders=host;x-amz-date,Signature=34254wgfoerge4rge"}, {"host", nil}, {"x-amz-date", "20171001T210835Z"}], [])
    (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/rest_query.ex:19: ExAws.Operation.ExAws.Operation.RestQuery.perform/2
```
What am i missing?

**Comment by ksheurs** [comment]
We're trying to get this to work, as well. IoT is a JSON resource, so our understanding is you can use `ExAws.Operation.JSON`. Upon adding the following to the config `@defaults`:

```elixir
iot: %{
  host: {"$region", "iot.$region.amazonaws.com"},
  scheme: "https://",
  region: "us-east-1",
  port: 443,
  service_override: :"execute-api"
}
```

.. we'd expect the following to work, but we receive a Cloudfront exception:

```elixir
ExAws.Operation.JSON.new(:iot, %{
  http_method: :get,
  path: "/things",
  headers: [
    {"content-type", "application/x-amz-json-1.1"},
  ]
}) |> ExAws.request
```

With the same AWS key/secret and request headers, we can get this to work via an API client like Postman. Any ideas @benwilson512?

**Comment by kuffel** [comment]
I found a solution. I had to specify the config myself, i think it is because it is missing in ExAws.Config.Defaults

This snippet should work:
```
def demo() do
   query = %ExAws.Operation.RestQuery{
      http_method: :get,
      path: "/things",
      params: %{},
      body: "",
      service: :"execute-api",
      parser: &ExAws.Utils.identity/2
    }
    config = %{
      :access_key_id => Application.get_env(:ex_aws, :access_key_id),
      :secret_access_key => Application.get_env(:ex_aws, :secret_access_key),
      :region => Application.get_env(:ex_aws, :region),
      :http_client => HTTPoison,
      :json_codec => Poison,
      :scheme => "https",
      :host => "iot." <> Application.get_env(:ex_aws, :region)<> ".amazonaws.com",
      :port => 443
    }
    ExAws.Operation.perform(query, config)
end

```

**Comment by benwilson512** [comment]
You're definitely on the right track. ExAws only includes default configuration for known services. If you want to add it as a service please consult the recently updated https://github.com/ex-aws/ex_aws/blob/master/CONTRIBUTING.md

**Comment by tejpochiraju** [comment]
Hi all, 

I wrote a small Python based code generator to create the type-specced Elixir module for the IoT service. I am looking for folks to help test and improve the generator.

The generator [is here](https://github.com/IoTReady/ex_aws_codegen) and the generated module [is here](https://gist.github.com/tejpochiraju/d32d80daf9982e5dc7853d8db17cd35b). I couldn't get the formatting right in the gist but you should be able to reformat it in your code editor.

Thanks,

**Comment by bernardd** [comment]
Hey @tejpochiraju - this looks lie a great start. A few suggestions I'd make:

Elixir has its own templating language (https://hexdocs.pm/eex/EEx.html), which may or may not be easier to deal with than using python (not that there's anything wrong with python, just wanted to make sure you were aware of the option).

To make your generated code a little more readable, you can run `mix format` over it - that'll handle indentation, line length etc in an Elixir-standard manner.

And as a final thought, if you'd like this to end up as a project under the ExAws umbrella (which I would very much welcome), the functions should only generate and return the request objects, and let the caller explicitly pass those to `ExAws.request` (which then allows them to add their own opts/config to the request). Also please check out https://github.com/ex-aws/ex_aws/blob/master/CONTRIBUTING.md as Ben posted above.

Good luck!

**Comment by tejpochiraju** [comment]
Thanks @bernardd - I was planning to migrate to Jinja if the generated code worked (seems to, tried a few queries).

- I am familiar with EEx but not with Elixir CLI tools, let me brush up. 
- Will run `mix format` - I think it's a spaces vs tabs issue here when pasting into Github Gists. 
- I will change it so only a query is returned
- When I have some time next week, I will try and generate tests too - to check if correct queries are returned as well as integration tests with `ExAws.Request` 
- Also planning to add an option to generate code for JSON services

A couple of questions:
- I am currently skipping optional parameters when generating the spec to make it simpler to call the generated functions. I was wondering if there was a way to define the complete objects somewhere, perhaps with `nil` defaults for the optional keys. These definitions would act as a reference for the gamut of options available without getting in the way each time.
- What would you like in the project - the code generator or the generated module? 
  - There some (minor) inconsistencies in the AWS JSON spec. I ran into one issue while generating for AWS IoT with the parameter `certificate_id` and had to add an exception to handle it. I assume that's going to be the case for other services too. 
  - In this case, anyone using the generator will need to compile and look for failures.

**Comment by tejpochiraju** [comment]
- I have updated the generator to use Jinja - much cleaner and easier to reason with. 
- Each function now returns a query
- I am running `mix format` at the end of generation.

The code still compiles and the queries seem to work. I have updated the [gist too](https://gist.github.com/tejpochiraju/d32d80daf9982e5dc7853d8db17cd35b).

**Comment by bernardd** [comment]
> I am currently skipping optional parameters when generating the spec to make it simpler to call the generated functions. I was wondering if there was a way to define the complete objects somewhere, perhaps with nil defaults for the optional keys. These definitions would act as a reference for the gamut of options available without getting in the way each time.

Yep - there's a couple of ways to approach it. The first is to just use default parameters:

`def some_op(param1, param2, optional_param1 \\ nil, optional_param2 \\ nil) do ...`

The second is to just provide an optional options list:

`def some_op(param1, param2, opts, \\ []) do ...`

In the latter case the caller does something like

`some_opt(param1, param2, optional_param2: op2_value)`

and it's up to the function to extract the values.

The second way is probably better if you have more than one or two optional parameters, since it keeps the function arity lower. Having said that, for ex_aws_chime which I wrote not so long ago, I used the first form, though I don't think any functions had more than 3 optional parameters.

In terms of what goes in the project, I think the ideal would be to have just the generated code, along with the generator as an external dependency and a mix target that will re-generate the code.

Thanks!

**Comment by bernardd** [comment]
I should add that for the ex_aws_chime case, some calls had sub-objects - for those cases I ended up defining a full module/struct for them, which allows the specs for the functions to be fairly clean - feel free to take a look, though please don't take is as the One True Way to do things :)

**Comment by tejpochiraju** [comment]
Alright, let me take a look at `ex_aws_chime`. I am using the generated `ex_aws_iot` module and compiling a list of usability improvements. I should have time this week to fix up the generator a bit more.
