### ISSUE TITLE
put_object_acl example?

### ISSUE THREAD

**Issue by hopewise** [ex-aws/ex_aws#490]
I've managed to upload a file to S3 bucket, but how would I grant public access to the uploaded file?
I've checked docs, but could know how to..
Is there any example about using `put_object_acl` ?

**Comment by benwilson512** [comment]
What have you tried so far?

**Comment by hopewise** [comment]
I've tried other library `{:arc, "~> 0.8.0"}` which can upload file to S3 and make it public using `@acl :public_read` inside the custom module that uses `Arc.Definition`

**Comment by benwilson512** [comment]
I've now made this more clear via https://github.com/ex-aws/ex_aws/blob/master/ISSUE_TEMPLATE.md, but the issue tracker is not really the place to ask for help. Please ask on the forums, IRC, or slack about how to use arc or ExAws.

**Comment by cokron** [comment]
I am facing the same issue, @benwilson512. There is a #FIXME in the code at `put_object_acl` and the arity is 3 with no config passed in. I would have expected a `ExAws.Config.new(:s3)` to go in as first argument. Not getting this to work…

**Comment by benwilson512** [comment]
`put_object_acl` creates an operation struct, it isn't the place for config, config is used on request. As noted in the comment you are replying to, this is not the place to seek help. Please do so on the forms, irc, or slack.
