### ISSUE TITLE
RedShift support

### ISSUE THREAD

**Issue by mayppong** [ex-aws/ex_aws#499]
Hi there,

I have been using `ex_aws` at work; and as we are adding Redshift to our project, I hope to continue using `ex_aws` to handle all API requests to Redshift. I noticed there is not RedShift support yet according to the list in README.

Is there any development work to support RedShift already? I would be happy to contribute but I notice the #497 mentioned that there is a plan to break up the package into individual services already. How can I best contribute to RedShift support for `ex_aws`?

**Comment by bruce** [comment]
@benwilson512 Would it make sense for this to happen post the planned v2 changes?

@mayppong If you're not aware of the plans there, take a peek at https://elixirforum.com/t/proposal-exaws-2-0/9269

**Comment by mayppong** [comment]
Since the breaking up for ExAws components has been decided on for version 2, I've started a new project for RedShift functionality under a new repo. You can find it here:
https://github.com/mayppong/ex_aws_redshift

**Comment by benwilson512** [comment]
Thanks! I'll create an `ex_aws_redshift` project here soon and then you can do a PR into that.
