### ISSUE TITLE
Start tagging releases

### ISSUE THREAD

**Issue by tompave** [ex-aws/ex_aws#506]
Would it be possible to resume `git tag -a`'ing the Hex releases? Or posting the release notes on github? At the moment it's a bit difficult to understand what was released, and when.

For example, 1.1.5 is on Hex, but there no entry in `CHANGELOG.md` and no tag.

**Comment by benwilson512** [comment]
2.0.0 and 2.0.1 are both tagged, I'll be sure to stay on top of it.
