### ISSUE TITLE
ElasticLoadBalancing support

### ISSUE THREAD

**Issue by fmcgeough** [ex-aws/ex_aws#510]
I've created an ex_aws service for ElasticLoadBalancing. I'm starting integration testing now. It's far enough along that I thought it'd be good to create an issue to let you know about it. 

My repo: https://github.com/fmcgeough/ex_aws_elastic_load_balancing

**Comment by fmcgeough** [comment]
I updated my repo to work with the released 2.0.1 version. testing with it now.

**Comment by fmcgeough** [comment]
This repo is now updated to work with both Classic Load Balancers (version "2012-06-01") and Application/Network Load Balancers (version "2015-12-01"). It works fine with the current (> 2) ex_aws. We are actively using this at our company by just pointing at my github repo.

**Comment by benwilson512** [comment]
Sorry for just getting to this: https://github.com/ex-aws/ex_aws_elastic_load_balancing PR welcome!
