### ISSUE TITLE
cognito sub-repository

### ISSUE THREAD

**Issue by olivermt** [ex-aws/ex_aws#511]
Hi.

We're ready to release cognito module.

Please create the repo and we'll PR it in.

**Comment by michalmuskala** [comment]
The current module is present at: https://github.com/omt-tech/ex_aws_cognito

It doesn't support yet all cognito features (since there's a lot of them), but those can be easily added as needed.

**Comment by benwilson512** [comment]
Done https://github.com/ex-aws/ex_aws_cognito_idp

Please create a PR to setup master so I can do a quick review, and then you'll be all set. You've already been added as contributors.

Thanks!
