### ISSUE TITLE
Credential Provider Chain Issues

### ISSUE THREAD

**Issue by vishalkuo** [ex-aws/ex_aws#518]
I'm cross-posting here from an Elixir Forum [topic](https://elixirforum.com/t/ex-aws-default-provider-chain-issues/10106). 

Essentially, I believe that `ex-aws`'s credential provider chain seems divergent from how most other AWS SDKs function when it comes to integration with credential files. It is my belief that checking the AWS credential files should be part of the default provider chain process and I am trying to understand why `ex-aws` does not conform to that standard.

The topic has more details.

**Comment by benwilson512** [comment]
Hey, let's continue the discussion there and then create an issue here when there are concrete objectives.
