### ISSUE TITLE
list_endpoints_by_platform_application ?

### ISSUE THREAD

**Issue by hopewise** [ex-aws/ex_aws#519]
I am trying to use:

    ExAws.SNS.list_endpoints_by_platform_application

however, I get this error:

```
** (UndefinedFunctionError) function ExAws.SNS.list_endpoints_by_platform_application/1 is undefined or private. Did you mean one of:

      * list_platform_applications/0
      * list_platform_applications/1

```

isn't list_endpoints_by_platform_application implemented?

also, howcome I can't find `sns.ex` file in the repo?!

**Comment by hopewise** [comment]
After a while, I could retrieve results as:

    ExAws.SNS.list_endpoints_by_platform_application(platform_application_arn,[])

however, the User Data is not retrieved ,which is shown in the AWS console  as User Data:

![screen shot 2017-11-26 at 5 10 39 pm](https://user-images.githubusercontent.com/1061157/33241360-ce354b8c-d2cc-11e7-9ea5-def72c56e3d4.png)

Any idea please?

**Comment by benwilson512** [comment]
Please follow the
