### ISSUE TITLE
ExAws Config Overriding Not Applying When Config File Present

### ISSUE THREAD

**Issue by vishalkuo** [ex-aws/ex_aws#521]
Followup from the elixirforum thread [here](https://elixirforum.com/t/exaws-config-overriding-not-applying/10577)

### Environment

* Elixir version: 1.5.2
* ExAws version: 2.0.2
* Hackney version: 1.10.1

### Current behavior

Trying to override the region of requests in the following manner results in an error. 

```elixir
iex(2)> conf = ExAws.Config.new(:sqs, [region: "us-west-1"])
%{access_key_id: "MY_ACCESS_KEY_ID", host: "sqs.us-west-1.amazonaws.com",
  http_client: ExAws.Request.Hackney, json_codec: Poison, port: 443,
  region: "us-east-1",
  retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000],
  scheme: "https://",
  secret_access_key: "MY_SECRET_KEY"}

iex(4)> ExAws.SQS.list_queues() |> ExAws.request(conf)
{:error,
 {:http_error, 403,
  %{code: "SignatureDoesNotMatch", detail: "",
    message: "Credential should be scoped to a valid region, not 'us-east-1'. ",
    request_id: "my_request_id", type: "Sender"}}}
```

It is important to notice that my `~./aws/config` file has its region set to `us-east-1`; however, it should still be possible to override this. 

### Expected behavior

The above snippet should return a configuration map equivalent to the following:
```elixir
iex(4)> conf2 = conf |> Map.merge(%{:region => "us-west-1"})
iex(5)> ExAws.SQS.list_queues() |> ExAws.request(conf2) # returns the correct result
```

**Comment by superhawk610** [comment]
We just ran into this as well - the issue is that `ExAws.Config.retrieve_runtime_config/1` overrides _all_ properties set in `~/.aws/{config, credentials}`, not just those specified. I'll open a PR to resolve shortly.
