### ISSUE TITLE
New ex_aws_cloudwatch

### ISSUE THREAD

**Issue by fmcgeough** [ex-aws/ex_aws#522]
My coworker and I have developed a ex_aws package service. Our ex_aws_cloudwatch package covers the entire monitoring API ("2010-08-01" version). We are using our package for an internal project. We'd like to help anyone else by making this publicly available in hex.pm. Should we just rename it to publish to hex since there already is an ex_aws_cloudwatch package (the existing one only implements one function in that API - describe_alarms)? or could we get our work into the existing project? https://github.com/JustinTangg/ex_aws_cloudwatch

**Comment by benwilson512** [comment]
Hey, this is awesome! Would it work to do a PR to https://github.com/ex-aws/ex_aws_cloudwatch ?

**Comment by fmcgeough** [comment]
sure! We are adding the parsing of responses now and we'll do PR after that's done and tested.

**Comment by benwilson512** [comment]
perfect, thanks!
