### ISSUE TITLE
[CONTRIBUTION] presigned urls do not support setting s3 custom metadata

### ISSUE THREAD

**Issue by supernullset** [ex-aws/ex_aws#524]
Hi there!

I recently have been working on a system that uploads files to S3 via pre-signed url (very standard, it works exactly as you would expect it to), after working with it for a time, I decided to take advantage of [S3 custom metadata](http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#UserMetadata). After getting errors consistently for a time, I ended up going for a dive into ExAws because I suspected that the signatures it was returning were not correct. I discovered that the [build_amz_query_params](https://github.com/ex-aws/ex_aws/blob/master/lib/ex_aws/auth.ex#L203-#L216) does not support signing any headers other than `host` (sad 🐼)! I put together a patch for `ex_aws` [here](https://github.com/ex-aws/ex_aws/compare/master...supernullset:sewillia/signed-custom-headers) and a patch for `ex_aws_s3` [here](https://github.com/ex-aws/ex_aws_s3/compare/master...supernullset:sewillia/patch-against-sewillia-fork). I opted for the `boto3`(python lib) approach for setting custom metadata via an optional parameter in the same way as `query_params`.

Onto my question: Is this solution acceptable enough that I should update docs and work my way back up the `ex_aws` stack? I ask because changing the airity of the `presigned_url` function feels "big" as changes go, and it may require updating other `ex_aws` modules. I am very happy to work with you to get a fix in however that needs to be done - I can run my project off of my fork until this is resolved. If it would be more helpful for me to open a PR in order to facilitate in-line conversation just let me know!

**Comment by benwilson512** [comment]
This sounds good, please open PRs.

**Comment by mohandass-pat** [comment]
Hey, Is this feature added?. If there is any way to set custom metadata in the PUT method Presigned URL? Can you please share any examples for that? 

Thanks in advance
