### ISSUE TITLE
Add endpoints for Amazon SageMaker

### ISSUE THREAD

**Issue by qyc** [ex-aws/ex_aws#527]
I'm looking to implement a client for the new [Amazon SageMaker API endpoints](http://docs.aws.amazon.com/general/latest/gr/rande.html#sagemaker_region). However, I found out that they are not included in `priv/endpoints.exs`, and thus simply using `ExAws.Operation.JSON.new(:sagemaker, ...)` would not work.

I would like to create a PR to include them, but I'm not sure how `priv/endpoints.exs` was created. It appeared to be automatically generated based on [aws-sdk-go](https://github.com/aws/aws-sdk-go/blob/master/models/endpoints/endpoints.json), which doesn't have the SageMaker endpoints yet. Is it okay to manually add them to `priv/endpoints.exs`?

**Comment by benwilson512** [comment]
Handled in master.
