### ISSUE TITLE
S3: Unable to set policy conditions for presigned urls

### ISSUE THREAD

**Issue by sgessa** [ex-aws/ex_aws#535]
Newbie question but I couldn't find a solution.
Is setting policy conditions for presigned url supported?
I see I can set expires_in, virtual_host and query_params but I'd need my policy to be like this:

```
"expiration": "'.date('Y-m-d\TG:i:s\Z', time()+10).'",
"conditions": [
    {"bucket": "xxx"},
    {"acl": "public-read"},
    {"success_action_redirect": "xxx"},
    ["starts-with", "$Content-Type", "image/jpeg"],
    ["content-length-range", 0, 10485760]
]
```

It's important for me to be able to check for content type and length.. am I missing anything?

**Comment by sgessa** [comment]
Hi, what's the reason?

**Comment by benwilson512** [comment]
Hey @sgessa the main reason is that this belongs on the `ExAws.S3` project not this one.
