### ISSUE TITLE
CodeBuild support

### ISSUE THREAD

**Issue by davepersing** [ex-aws/ex_aws#536]
Hi Ben!  Thanks for your work here.  It's very much appreciated!

I have been working on a CodeBuild ex_aws module and would love to get it included here.  

If possible, I'd love a code review, too.  The CodeBuild API uses lower camelCase parameter names, so it made things a little more complicated.  The docs also don't exist yet, and it hasn't been published to Hex.  Happy to do that once it's had some more eyes on it.  

Code is here:  https://github.com/davepersing/ex_aws_code_build

Thanks again!

**Comment by davepersing** [comment]
@benwilson512 - Hey Ben!  Wasn't sure if you had a chance to check this out or not.  No worries if not.  :)

**Comment by benwilson512** [comment]
Hey! Sorry I missed this.

Please create a PR on https://github.com/ex-aws/ex_aws_code_build and we'll go from there.

**Comment by davepersing** [comment]
No worries!  Will put the PR up tonight.  Thank you sir!
