### ISSUE TITLE
AuthorizationHeaderMalformed the authorization header requires three components: Credential, SignedHeaders, and Signature

### ISSUE THREAD

**Issue by xlexi** [ex-aws/ex_aws#537]
### Environment
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.6.1 (compiled with OTP 20)

* ex_aws 2.0.2 (Hex package) (mix)
* ex_aws_s3 2.0.0 (Hex package) (mix)

* hackney 1.10.1 (Hex package) (rebar3)

### Current behaviour
When attempting to upload an object or perform any other operation I receive the following error   
```elixir
    {:error, 
   {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature.</Message><RequestId>4EEC077613405D58</RequestId><HostId>EN+gsRgCJbk7iZrXpGTDS/eu/Ktz0O3gJ1OUnLjHN2FMMqcUR3pkLa6pb76ed3/8tUlH4jjx9wE=</HostId></Error>", 
headers: [
   {"x-amz-request-id", "4EEC077613405D58"}, 
   {"x-amz-id-2", "EN+gsRgCJbk7iZrXpGTDS/eu/Ktz0O3gJ1OUnLjHN2FMMqcUR3pkLa6pb76ed3/8tUlH4jjx9wE="}, 
   {"Content-Type", "application/xml"}, 
   {"Transfer-Encoding", "chunked"}, 
   {"Date", "Sun, 18 Feb 2018 13:51:31 GMT"}, 
   {"Connection", "close"}, 
   {"Server", "AmazonS3"}], 
   status_code: 400}
}}
```    
   
Config:   
```elixir
config :ex_aws, :s3,
  access_key_id: System.get_env("RFG_AWS_ACCESS_KEY_ID"),
  secret_access_key: System.get_env("RFG_AWS_SECRET_ACCESS_KEY"),
  region: "us-east-2",
  host: "s3.us-east-2.amazonaws.com",
  scheme: "https://"
```

### Expected behaviour
The library successfully sends a request

**Comment by benwilson512** [comment]
As a first effort make sure to update hackney. You also only need to include `region`, `host` and `scheme` will be computed for you unless you're hitting some S3 clone.

**Comment by xlexi** [comment]
First of, thank you for the amazingly quick response.   
Hackney has been updated, but the error remains
``` * hackney 1.11.0 (Hex package) (rebar3) ```   
   
Host and scheme was put there in an attempt to debug the issue, but I have removed them now.

**Comment by benwilson512** [comment]
Hm, I’ll have to take a look when I get home. Can you provide an example
request you’re making?

ExAws hasn’t had any new releases in a bit, so my money is still on
something hackney related, but I’ll have to try to some versions.

**Comment by xlexi** [comment]
The request I am testing with is 
```elixir
image =
      ExAws.S3.put_object(@bucket_name, "#{@avatar_location}/#{avatar_identifier}.jpg", image_binary)
      |> ExAws.request!
```   
 I have been mostly following this guide on Medium https://medium.com/@jackacarlisle/image-uploads-with-aws-s3-elixir-phoenix-ex-aws-step-3-568ca6360c63?token=l-k8E3qGoM0e1ZRA and the ex_aws_s3 documentation.    
   
Thank you for your time

**Comment by benwilson512** [comment]
Can you provide an example avatar identified? I’m wondering if there’s an
odd character in there. Does it work with a simple ASCII path?

**Comment by benwilson512** [comment]
I just ran a basic test locally with Hackney 1.11 without issue, so my current guess is that it's related to the `avatar_identifier`. Can you supply the full interpolated string?

**Comment by xlexi** [comment]
the avatar identifier is merely a UUID. The fully interpolated string is ```avatar/4ca9c26b-c729-5357-8dd8-60ce3396677b.jpg```  I just tried changing it to ```test.jpg```  and received the same error

**Comment by benwilson512** [comment]
Weird. Can you add the following to your config?

```
config :ex_aws, debug_requests: true
```

And then show the output for a request?

**Comment by xlexi** [comment]
```
[debug] Request URL: "https://s3.us-east-2.amazonaws.com/thegm.testing/4ca9c26b-c729-5357-8dd8-60ce3396677b.jpg"
[debug] Request HEADERS: [{"Authorization", "AWS4-HMAC-SHA256 Credential=ACCESSKEYIDINPLAINTEXT/20180219/us-east-2/s3/aws4_request,SignedHeaders=content-length;host;x-amz-content-sha256;x-amz-date,Signature=40349d9d994310582eb6e1fe6c920211e621f930a0fe4bfa2a97db12b89bba88"}, {"host", "s3.us-east-2.amazonaws.com"}, {"x-amz-date", "20180219T155915Z"}, {"content-length", 70659}, {"x-amz-content-sha256", "f41ddb1578f8a06c210f343920a54f08418534922c9492e06cc119e96d5308a1"}]
[debug] Request BODY: <<255, 216, 255, 224, 0, 16, 74, 70, 73, 70, 0, 1, 1, 1, 0, 72, 0, 72, 0, 0, 255, 237, 36, 130, 80, 104, 111, 116, 111, 115, 104, 111, 112, 32, 51, 46, 48, 0, 56, 66, 73, 77, 4, 37, 0, 0, 0, 0, 0, 16, ...>>
[info] Sent 500 in 2459ms
[error] #PID<0.723.0> running Thegm.Endpoint terminated
Server: localhost:8090 (http)
Request: POST /users/xlexious/avatar
** (exit) an exception was raised:
    ** (ExAws.Error) ExAws Request Error!

{:error, {:http_error, 400, %{body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>AuthorizationHeaderMalformed</Code><Message>The authorization header is malformed; the authorization header requires three components: Credential, SignedHeaders, and Signature.</Message><RequestId>332F53489B93DF8C</RequestId><HostId>n+QwVBH01nDu/9XC1K6I0rlpRGH+ySutvyrBW+o95mAEZzvd+RnE1vkb56y48NBesRQckN38RKk=</HostId></Error>", headers: [{"x-amz-request-id", "332F53489B93DF8C"}, {"x-amz-id-2", "n+QwVBH01nDu/9XC1K6I0rlpRGH+ySutvyrBW+o95mAEZzvd+RnE1vkb56y48NBesRQckN38RKk="}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Mon, 19 Feb 2018 15:59:17 GMT"}, {"Connection", "close"}, {"Server", "AmazonS3"}], status_code: 400}}}

        (ex_aws) lib/ex_aws.ex:66: ExAws.request!/2
        (thegm) web/controllers/useravatars_controller.ex:29: Thegm.UserAvatarsController.create/2
        (thegm) web/controllers/useravatars_controller.ex:1: Thegm.UserAvatarsController.action/2
        (thegm) web/controllers/useravatars_controller.ex:1: Thegm.UserAvatarsController.phoenix_controller_pipeline/2
        (thegm) lib/thegm/endpoint.ex:1: Thegm.Endpoint.instrument/4
        (phoenix) lib/phoenix/router.ex:278: Phoenix.Router.__call__/1
        (thegm) lib/thegm/endpoint.ex:1: Thegm.Endpoint.plug_builder_call/2
        (thegm) lib/plug/debugger.ex:99: Thegm.Endpoint."call (overridable 3)"/2
        (thegm) lib/thegm/endpoint.ex:1: Thegm.Endpoint.call/2
        (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
        (cowboy) /Users/alex/TheGM/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
```

There you go,
I replaced the access key ID in the authorization header with ACCESSKEYIDINPLAINTEXT. Otherwise unaltered

**Comment by xlexi** [comment]
Sorry for wasting your time, it turned out to be an invisible formatting character in the access key. It would be nice if AWS gave a 401 for invalid credentials like it's supposed to, but what can you do

**Comment by benwilson512** [comment]
Oh weird! Glad you could figure it out!

**Comment by IskanderMustafin** [comment]
Got same error. Reason was accidentally added comma to the end of `AWS_SECRET_ACCESS_KEY`. I.e. it was `XXX,` instead of `XXX`

**Comment by natanb830** [comment]
same mistake like @IskanderMustafin - added comma to the end of AWS_SECRET_ACCESS_KEY...

**Comment by ricardomesmo** [comment]
> Got same error. Reason was accidentally added comma to the end of `AWS_SECRET_ACCESS_KEY`. I.e. it was `XXX,` instead of `XXX`

Hey, yet 2024 i got the same mistake, and @IskanderMustafin fix it, thank you
