### ISSUE TITLE
special characters in file's name

### ISSUE THREAD

**Issue by safwanolaimat** [ex-aws/ex_aws#544]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version): elixir -> 1.5 , erlang -> Erlang/OTP 20
* ExAws version `mix deps |grep ex_aws` : ex_aws 2.0.2 
* HTTP client version. IE for hackney do `mix deps | grep hackney` : hackney 1.11.0

### Current behavior
When Provided with a file that has a special character in its name the library will upload it anyway resulting in an error 405 or 403 coming back from Amazon S3
### Expected behavior
library should not accept files with special characters in their name 
or should encode file's name using for example percent encoding

**Comment by benwilson512** [comment]
This is an S3 specific issue.
