### ISSUE TITLE
ExAws.S3.download_file fails due to no match in ExAws.request

### ISSUE THREAD

**Issue by andyleclair** [ex-aws/ex_aws#547]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.0
* ExAws version `mix deps |grep ex_aws`: 2.0.2
* HTTP client version. IE for hackney do `mix deps | grep hackney`: hackney@1.11.0

### Current behavior

I'm opening this issue here, since although it is involved with` ExAws.S3`, the issue appears to be here in `ExAws.request!`

```elixir
iex(1)> ExAws.S3.download_file("<bucket>", "<path>.tar.gz", "test.tar.gz") |> ExAws.request
** (CaseClauseError) no case clause matching: {:ok, %{headers: [{"x-amz-bucket-region", "us-west-2"}, {"x-amz-request-id", "6AA2BBE53D9CE19D"}, {"x-amz-id-2", <omitted>}, {"Content-Type", "application/xml"}, {"Transfer-Encoding", "chunked"}, {"Date", "Tue, 27 Mar 2018 21:30:16 GMT"}, {"Server", "AmazonS3"}], status_code: 301}}
    (ex_aws) lib/ex_aws/request.ex:38: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:40: ExAws.Operation.ExAws.Operation.S3.perform/2
    (ex_aws) lib/ex_aws.ex:61: ExAws.request!/2
    (ex_aws_s3) lib/ex_aws/s3/download.ex:51: ExAws.S3.Download.get_file_size/3
    (ex_aws_s3) lib/ex_aws/s3/download.ex:28: ExAws.S3.Download.build_chunk_stream/2
    (ex_aws_s3) lib/ex_aws/s3/download.ex:68: ExAws.Operation.ExAws.S3.Download.perform/2

```

It appears this status isn't handled here: https://github.com/ex-aws/ex_aws/blob/master/lib/ex_aws/request.ex#L39

### Expected behavior

There should be a matching clause for this status

**Comment by benwilson512** [comment]
A 301 redirect generally means that the bucket you're requesting is in a region other than the one that is configured. What region is the bucket in and what region do you have configured?

**Comment by andyleclair** [comment]
The bucket is in us-west-2, I've configured for the same

**Comment by benwilson512** [comment]
The error that you have here shows `status_code: 301` so that's the real issue to figure out here. If you do `ExAws.Config.new(:s3)[:host]` what do you get?

**Comment by andyleclair** [comment]
I was incorrect! I could've sworn I'd passed the region in before and it was failing. The example I'd given above was just a quickie for illustrative purposes. If I give the right region in `ExAws.request` it does appear to work.

Still, it would be worth improving the error message. I can submit a PR to make this a little more obvious for the next dunce who's out to make a public ass of themselves

**Comment by benwilson512** [comment]
Not a problem haha, a PR would be welcome thanks.
