### ISSUE TITLE
DMS service module

### ISSUE THREAD

**Issue by lackac** [ex-aws/ex_aws#556]
Hello @benwilson512,

We created a new service module for AWS DMS. Currently it's minimal and only handles listing, starting, and stopping DMS replication tasks. It can be extended in the future as needed.

It's currently at https://github.com/100Starlings/ex_aws_dms and released to hex as [ex_aws_dms](https://hex.pm/packages/ex_aws_dms/). We would be happy to maintain it here under the `ex-aws` org.

**Comment by benwilson512** [comment]
PR welcome! https://github.com/ex-aws/ex_aws_dms Thank you!
