### ISSUE TITLE
Elixir 1.3 Support

### ISSUE THREAD

**Issue by dspencer001** [ex-aws/ex_aws#559]
Is the Elixir 1.4 requirement necessary in the core package? I ask because we want to use ExAws to get data from an SQS queue, and our systems run on Elixir 1.3, as Ubuntu has a package in the universe repository for 1.3. It looks like the Elixir 1.4 requirement was originally added due to a feature in the S3 package, so if it's not necessary now that ExAws is split into different repos, it would be great to get that relaxed to include 1.3.

Also, the SQS package requires at least Elixir 1.5. Is that also necessary? It looked like that was included in the initial commit, so if it doesn't require anything greater than 1.3 it would be great to get that relaxed as well.

I'm open to helping backport functionality if it's needed.

**Comment by benwilson512** [comment]
Elixir 1.3 came out nearly two years ago, and there are a multitude of official ways to get the latest Elixir versions on Ubuntu. I would urge you to look towards a more modern Elixir version.

You are welcome to try the core ExAws package on 1.3 and see how it goes. If you don't find issues, I can consider lowering it.

**Comment by dspencer001** [comment]
We strongly prefer to use packages included in the official Ubuntu repos. Elixir 1.3 will officially be maintained for security updates at least until 1.8 comes out, according to this: https://hexdocs.pm/elixir/master/compatibility-and-deprecations.html#content

At least basic functionality for both the core package and SQS appears to work on 1.3 without any warnings. I'll try to get the tests running as well to verify that.

**Comment by benwilson512** [comment]
> We strongly prefer to use packages included in the official Ubuntu repos.

I'd be curious to understand what underlies this preference. Erlang Solutions offers and maintains Ubuntu packages that are usable through apt and are generally far more up to date.

**Comment by dspencer001** [comment]
Packages in Debian and Ubuntu follow packaging guidelines. They put files in the right places, express dependencies correctly, and version in the repo correctly. We consistently have issues with all of those with non-distro packages. We get security updates and tested compatibility as well.

**Comment by asummers** [comment]
I think this issue can be closed as 1.3 is no longer supported per the link in https://github.com/ex-aws/ex_aws/issues/559#issuecomment-388571271

**Comment by dspencer001** [comment]
Yeah, I'll close it.
