### ISSUE TITLE
Secrets Manager Service Module

### ISSUE THREAD

**Issue by bmanuel** [ex-aws/ex_aws#565]
I have created a new service module for Secrets Manager. It is currently hosted at https://github.com/bmanuel/ex_aws_secretsmanager. If it is satisfactory, I would love to transfer it into the ex-aws org.

Also, it will require the additional endpoints for secrets manager that are in https://github.com/ex-aws/ex_aws/pull/564.

**Comment by benwilson512** [comment]
Great! Please create a PR here: https://github.com/ex-aws/ex_aws_secretsmanager/tree/master
