### ISSUE TITLE
ExAws.Error message returns a string of the hackney error, add function to access actual error tuple.

### ISSUE THREAD

**Issue by GrandathePanda** [ex-aws/ex_aws#572]
### Current behavior

Not a bug really but, I question the usefulness of the current error implementation. Right now when ExAws.Error is raised the message is the string,

`ExAws Request Error!\n\n{:error, {:http_error, 404, %{body: \"<?xml version=\\\"1.0\\\" encoding=\\\"UTF-8\\\"?>\\n<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>***********</BucketName><RequestId>48E92B0AA558EB3C</RequestId><HostId>**********</HostId></Error>\", headers: [{*************************}]\"}, {\"Content-Type\", \"application/xml\"}, {\"Transfer-Encoding\", \"chunked\"}, {\"Date\", \"Sat, 30 Jun 2018 21:35:54 GMT\"}, {\"Connection\", \"close\"}, {\"Server\", \"AmazonS3\"}], status_code: 404}}}\n"`

This is super not useful for me personally, I'd really rather have access to what looks like the Hackney error tuple that is interpolated in there for things like its status code and response body. I checked the docs for the error module and there doesn't seem to be something like that already.

### Feature Request

Add a function to ExAws.Error to return the underlying Hackney error tuple

I'd be happy to take a crack at implementing this and submitting a PR.

**Comment by benwilson512** [comment]
Hey @GrandathePanda it sounds like you just want to use `ExAws.request` instead of `ExAws.request!. The former simply returns errors as a tuple, while the latter raises an exception. If you're choosing the `!` form and then catching the exception, you probably should just use the `request` function.

**Comment by GrandathePanda** [comment]
This is happening through the broken out s3 package, I imagine they are calling request! internally for ExAws.S3.put_object/4. After checking out their implementation should I go ahead and move this request to them?

**Comment by benwilson512** [comment]
Well that package is also me. Regardless though, neither `put_object` nor any of the other S3 functions actually call `ExAws.request`, they all just build operation structs which you pass to one of the request functions. Can you show the exact code you're running to produce the error?

**Comment by GrandathePanda** [comment]
Yup I misunderstood, I took a look at the code and indeed was using the ! form, sorry about that, that's what I get for copying from examples without looking closer :P
