### ISSUE TITLE
xml-builder version constrains

### ISSUE THREAD

**Issue by thonydam** [ex-aws/ex_aws#575]
Hi!

Could we bump the version of `xml_builder` to the latest one `2.1`?

Thanks!

**Comment by benwilson512** [comment]
Ah, I should remove the xml builder dep from this library entirely, it belongs on the service library

**Comment by benwilson512** [comment]
PR welcome.

**Comment by archSeer** [comment]
This issue can be closed now! :)

**Comment by mtarnovan** [comment]
Looks like the dependency is back: https://github.com/ex-aws/ex_aws/blob/v2.1.0/mix.exs#L39

Is this accidental?

**Comment by Odaeus** [comment]
@mtarnovan I just came here after hitting this issue due to a dependency conflict. If I'm reading the repo history correctly, it looks like a version with `xml_builder` removed hasn't been released.

**Comment by angelikatyborska** [comment]
Looks like `ex_aws v2.1.1` was released on hex 4 days ago and this dependency conflict is now gone. However, there is no git tag for `v2.1.1` (at this moment) to have linkable proof.
