### ISSUE TITLE
Request method in ex_aws_sqs, sqs.ex is incomplete 

### ISSUE THREAD

**Issue by utkarshvaish9** [ex-aws/ex_aws#577]
### Environment

ex_aws_sqs

### Current behavior

    defp request(queue, action, params) do
    action_string = action |> Atom.to_string |> Macro.camelize

    %ExAws.Operation.Query{
      path: "/" <> queue,
      params: params |> Map.put("Action", action_string),
      service: :sqs,
      action: action,
      parser: &ExAws.SQS.Parsers.parse/2
    }
     end
It ends by only creating an operation. It is not calling the perform method which actual request method calls, thus it just create the operation and not doing the exact action. It is a big bug because it is hindering all the method's defined in that file. For ex: if we call ExAws.SQS.receive_message(queue_name), it will just create the operation and won't perform the action of receiving the message. For the message to be received, perform method needs to be called explicitly for receiving the message.

### Expected behavior

ExAws.SQS.receive_message(queue_name) should directly be able to receive messages without explicitly calling the perform method

**Comment by benwilson512** [comment]
This is a design decision not a bug. The ExAws readme shows how to use these structs.
