### ISSUE TITLE
ExAws Operation Error

### ISSUE THREAD

**Issue by collegeimprovements** [ex-aws/ex_aws#581]
### Environment

* Elixir & Erlang versions (elixir --version): 1.6.6
* ExAws version `mix deps |grep ex_aws`: 2.1.0
* HTTP client version. IE for hackney do `mix deps | grep hackney`: 1.13.0

### Current behavior

```elixir
 operation = %ExAws.Operation.JSON{
      http_method: :post,
      service: :translate,
      path: "/",
      data: %{"Text" => "你好，世界", "SourceLanguageCode" => "auto", "TargetLanguageCode" => "en"},
      headers: [{"content-type", "application/x-amz-json-1.0"}]
    }

operation |> ExAws.request()
```
The above gives: `{:error, {:http_error, 500, "<InternalFailure/>\n"}}`.

### Expected behavior

It should return `translated-text: Hello world`

<img width="592" alt="screen shot 2018-07-24 at 11 57 56 am" src="https://user-images.githubusercontent.com/1519705/43124498-ff2e5f28-8f44-11e8-9d91-a9183a678fc4.png">

Ref:[ GO-SDK](https://github.com/aws/aws-sdk-go/blob/master/models/apis/translate/2017-07-01/api-2.json)

I tried `no-header` as well as the follwing headers:
```elixir
{"content-type", "application/x-amz-json-1.0"},
{"amz_target", "AWSShineFrontendService_20170701.TranslateText"}
```
[Amazon Translate Service](https://console.aws.amazon.com/translate/home?region=us-east-1#explorer)
<img width="884" alt="screen shot 2018-07-24 at 1 37 04 pm" src="https://user-images.githubusercontent.com/1519705/43125166-d4689a68-8f46-11e8-9b31-a9082f0ed67c.png">

**Comment by benwilson512** [comment]
You probably want to set the following in your config.exs

```
config :ex_aws, debug_requests: true
```

I'll try to help, but do realize that this still isn't what the issue tracker is for. I can't personally be responsible for helping every person figure out how every AWS API works. The issue tracker is for bugs in ExAws, that's it.

**Comment by benwilson512** [comment]
Based on https://docs.aws.amazon.com/translate/latest/dg/examples-sigv4.html I got this to work:

```
operation = %ExAws.Operation.JSON{
     http_method: :post,
     service: :translate,
     path: "/",
     data: %{"Text" => "你好，世界", "SourceLanguageCode" => "auto", "TargetLanguageCode" => "en"},
     headers: [
      {"content-type", "application/x-amz-json-1.1"},
      {"X-Amz-Target", "AWSShineFrontendService_20170701.TranslateText"}
    ]
   }

operation |> ExAws.request()
#=> {:ok,
 %{
   "SourceLanguageCode" => "zh",
   "TargetLanguageCode" => "en",
   "TranslatedText" => "Hello, world."
 }}
```

**Comment by collegeimprovements** [comment]
Thanks Ben.
