### ISSUE TITLE
Task.Supervised.stream(5000) multiple uploads

### ISSUE THREAD

**Issue by ijunaid8989** [ex-aws/ex_aws#592]
### Environment

* Elixir & Erlang versions (elixir --version): 1.7.2 & 21
* ExAws version `mix deps |grep ex_aws`: * ex_aws 1.1.5 (Hex package) (mix)
* HTTP client version. IE for hackney do `mix deps | grep hackney`: * hackney 1.10.1 (Hex package) (rebar3)

### Current behavior

I am trying to send multiple files using this as described in docs.

```
    upload_file = fn {src_path, dest_path} ->
      ExAws.S3.put_object("my-assets", dest_path, File.read!(src_path), [acl: :public_read])
      |> ExAws.request!
    end
    paths
    |> Task.async_stream(upload_file, max_concurrency: 10)
    |> Stream.run
```
my paths are like: 
```
%{      
  "storage/compa-ycqozxb/compa-ycqozxb.gif" => "crome-tidcz/compares/compa-ycqozxb/compa-ycqozxb.gif",
  "storage/compa-ycqozxb/compa-ycqozxb.mp4" => "crome-tidcz/compares/compa-ycqozxb/compa-ycqozxb.mp4",
  "storage/compa-ycqozxb/thumb-compa-ycqozxb.jpg" => "crome-tidcz/compares/compa-ycqozxb/thumb-compa-ycqozxb.jpg"
}
```
Each src file exists.

I am continuously getting this error as 
```
** (exit) exited in: Task.Supervised.stream(5000)
    ** (EXIT) time out
    (elixir) lib/task/supervised.ex:280: Task.Supervised.stream_reduce/7
    (elixir) lib/stream.ex:637: Stream.run/1
```

### Expected behaviour
It should upload all files smoothly ?

**Comment by ijunaid8989** [comment]
FYI: Filesizes are

Filesizes are: GIF: 3.1 MB MP4: 1.0 MB JPG: 97.4 KB

**Comment by benwilson512** [comment]
You should probably raise the timeout. Per the issue template though, please don't use the issue tracker for help, use the forums.

**Comment by jaeyson** [comment]
Raising `:timeout` worked, Thanks @benwilson512.
