### ISSUE TITLE
Cloudwatch ex aws, access to hex releases

### ISSUE THREAD

**Issue by cammellos** [ex-aws/ex_aws#599]
Hi @benwilson512 , sorry for contacting you here, we would like to release hex_cloudwatch, could you grant us access to do so on hex hex.pm?

https://github.com/ex-aws/ex_aws_cloudwatch/issues/11

Thanks!

**Comment by benwilson512** [comment]
Hey @cammellos I'd be happy to, can you provide me with the email address I should use?

**Comment by cammellos** [comment]
@benwilson512 any luck? Thanks!

**Comment by benwilson512** [comment]
@cammellos github only shows that it's been verified for me and a signature, no email address is displayed. Please shoot me an email at my github name @gmail.com with your email and I'll get you access.

**Comment by cammellos** [comment]
closing, thanks!
