### ISSUE TITLE
record type mappings error in ExAws.Utils.rename_keys/2

### ISSUE THREAD

**Issue by romanr321** [ex-aws/ex_aws#600]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Elixir & Erlang versions (elixir --version): 
    Erlang/OTP 21 [erts-10.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]
    Interactive Elixir (1.7.0) 

* ExAws version `mix deps |grep ex_aws`   
     {:poison, "~> 3.0"},
      {:configparser_ex, "~> 2.0"},
      {:ex_aws, "~> 2.0"},
      {:ex_aws_route53, "~> 2.0"},
    
* HTTP client version. IE for hackney do `mix deps | grep hackney`
      {:hackney, "~> 1.9"}

### Current behavior
> ExAws.Route53.list_record_sets("Z2M1FKI600VX4C", type: :a) |> ExAws.request()  
{:error,
 {:http_error, 400,
  %{
    body: "<?xml version=\"1.0\"?>\n<ErrorResponse xmlns=\"https://route53.amazonaws.com/doc/2013-04-01/\"><Error><Type>Sender</Type><Code>InvalidInput</Code><Message>1 validation error detected: Value 'a' at 'startRecordType' failed to satisfy constraint: Member must satisfy enum value set: [AAAA, A, CAA, NS, SOA, SPF, MX, PTR, CNAME, TXT, SRV, NAPTR]</Message></Error><RequestId>9b1c1317-e831-11e8-b1fb-13c43b8553d8</RequestId></ErrorResponse>",
    headers: [
      {"x-amzn-RequestId", "9b1c1317-e831-11e8-b1fb-13c43b8553d8"},
      {"Content-Type", "text/xml"},
      {"Content-Length", "431"},
      {"Date", "Wed, 14 Nov 2018 17:20:37 GMT"},
      {"Connection", "close"}
    ],
    status_code: 400
  }}}

### Expected behavior
{:ok, map with body = xml with list of type A records}

**Comment by benwilson512** [comment]
Please reopen this on the Route53 repo.
