### ISSUE TITLE
Missing support for the new eu-north-1

### ISSUE THREAD

**Issue by lawik** [ex-aws/ex_aws#610]
### Environment

* Elixir & Erlang versions (elixir --version): Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace] Elixir 1.7.3 (compiled with Erlang/OTP 21)
* ExAws version:
  ex_aws (Hex package) (mix)
  locked at 2.1.0 (ex_aws) b9265152
  ex_aws_s3 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_s3) 9e09366e

### Current behavior

Tried using the fresh new eu-north-1 region.

```
ExAws.Config.Defaults.get("s3", "eu-north-1")
** (RuntimeError) s3 not supported in region eu-north-1 for partition aws
    (ex_aws) lib/ex_aws/config/defaults.ex:118: ExAws.Config.Defaults.fetch_or/3
    (ex_aws) lib/ex_aws/config/defaults.ex:101: ExAws.Config.Defaults.do_host/3
    (ex_aws) lib/ex_aws/config/defaults.ex:42: ExAws.Config.Defaults.get/2
```

I'd add it myself and provide a PR, but I imagine there is a script to generate priv/endpoints.exs and I haven't found any way to do it.

### Expected behavior

Well, I've verified S3 works on eu-north-1 through the AWS cli. So I'd hope it works with this library too :)

Nice library to work with aside from this little show-stopper :)

**Comment by bernardd** [comment]
Looks like eu-north has been added for at least some services, so I'm gonna close this.. For future reference, endpoints.exs is hand-crafted, so feel free to add things via PRs as you find them.
