### ISSUE TITLE
Sub-libraries not swapping JSON codec or using region in config

### ISSUE THREAD

**Issue by foggy1** [ex-aws/ex_aws#616]
* Do not use the issues tracker for help or support (try Elixir Forum, Slack, IRC, etc.)
* Questions about how to contribute are fine.

### Environment

* Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
* *ex_aws 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (ex_aws) b9265152
* ex_aws_lambda 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_lambda) d1904b97
* hackney 1.15.0 (Hex package) (rebar3)
  locked at 1.15.0 (hackney) 287a5d23

### Current behavior

I have the following in my config

```
config :ex_aws, :our_app,
  region: "us-west-1",
  json_codec: Jason
```

and I have tried adding and removing the following as well

```
config :ex_aws_lambda, :our_app,
  region: "us-west-2",
  json_codec: Jason
```

When I make an ExAws.request() with any given ExAws.Lambda function, it tries to go to the default `us-east-1`, ignoring both configs.

Additionally, if I do not have Poison installed, AWS requests (when I specific `us-west-2` in the request) fail since they try to use Poison instead of Jason.

I have had a similar problem with the `ex_aws_cloudwatch` library on a separate project.

### Expected behavior

I expect the config to be respected since the docs indicate that it should be. I initially thought this was an issue in the sub-libraries but the error ends up falling back in the core ExAws operation library.

```
** (UndefinedFunctionError) function Poison.encode!/1 is undefined (module Poison is not available)
    Poison.encode!(%{the map i was trying to encode})
    (ex_aws) lib/ex_aws/request.ex:19: ExAws.Request.request/6
    (ex_aws) lib/ex_aws/operation/json.ex:49: ExAws.Operation.ExAws.Operation.JSON.perform/2
```

If the issue _is_ in the sub-libraries, it must just be a matter of propagating the config changes downwards. I would be happy to help with this if someone can point me in the right direction.

It's not hard to install Poison or to type `us-west-2` in my ExAws.request fields, but it seems silly that I should have to install two JSON libraries or specifiy a single region all over the place.

**Comment by benwilson512** [comment]
Hey @foggy1 sorry to hear you're having issues.

```
config :ex_aws, :our_app,
  region: "us-west-1",
  json_codec: Jason
```

Why are you doing config this way? Just do:

```
config :ex_aws,
  region: "us-west-1",
  json_codec: Jason
```

**Comment by foggy1** [comment]
Ugh, thank you.
