### ISSUE TITLE
ExAws: HTTP ERROR: :checkout_timeout under checkout_timeout threshold

### ISSUE THREAD

**Issue by foggy1** [ex-aws/ex_aws#622]
### Environment

* Elixir & Erlang versions (elixir --version):
Erlang/OTP 21 [erts-10.2.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21

* ex_aws 2.1.0 (Hex package) (mix)
* hackney 1.15.0 (Hex package) (rebar3)

### Current behavior

I have the following in my config
```
config :ex_aws, :hackney_opts,
  recv_timeout: 90_000,
  checkout_timeout: 30_000
```
Within 3 seconds of running my application and spinning up a bunch of my requests, I see a boatload of these:
```
ExAws: HTTP ERROR: :checkout_timeout
```

### Expected behavior

I expected no checkout timeout warnings until 30 seconds, unless I'm misunderstanding where to pass this opt or what it does.

This could be a hackney problem but it's hard to tell.

**Comment by benwilson512** [comment]
Yup this is indeed a hackney issue. It sounds like you're trying to make too many simultaneous requests for the pool size you have.
