### ISSUE TITLE
Having a hard time using ex_aws on Production

### ISSUE THREAD

**Issue by robertveloso** [ex-aws/ex_aws#623]
### Environment

* Elixir & Erlang versions (elixir --version): 1.8.1
* ExAws version `mix deps |grep ex_aws`: 2.1.0
* Ex_Aws_s3: 2.0
* HTTP client version. IE for hackney do `mix deps | grep hackney`: 1.12.1

### Current behavior

When trying to upload Image to Digital Ocean Spaces, I got the error:
20:13:50.449 [error] Task #PID<0.2568.0> started from #PID<0.2565.0> terminating
** (ArgumentError) argument error
    :erlang.iolist_to_binary(nil)
    (crypto) crypto.erl:415: :crypto.hmac/3
    (ex_aws) lib/ex_aws/auth/signatures.ex:15: ExAws.Auth.Signatures.signing_key/3
    (ex_aws) lib/ex_aws/auth/signatures.ex:7: ExAws.Auth.Signatures.generate_signature_v4/4
    (ex_aws) lib/ex_aws/auth.ex:129: ExAws.Auth.auth_header/7
    (ex_aws) lib/ex_aws/auth.ex:45: ExAws.Auth.headers/6
    (ex_aws) lib/ex_aws/request.ex:29: ExAws.Request.request_and_retry/7
    (ex_aws) lib/ex_aws/operation/s3.ex:39: ExAws.Operation.ExAws.Operation.S3.perform/2
Function: #Function<1.78569476/0 in Arc.Actions.Store.async_put_version/3>
    Args: []
20:13:50.451 [error] Ranch protocol #PID<0.2565.0> of listener CidadesWeb.Endpoint.HTTP (connection #PID<0.2564.0>, stream id 1) terminated
** (exit) :badarg

### Expected behavior

In development everything works great, I'm using docker to build the image(elixir:1.8.1-alpine) and then running in a VPS.

**Comment by benwilson512** [comment]
This seems like your keys are nil. If you do `ExAws.Config.new(:s3)` do you see keys? DO NOT post the value here, that will expose your keys.

**Comment by robertveloso** [comment]
Yes, this did the trick. Using that I notice the region as nil. changing 
region: System.get_env("S3_REGION") to 
region: [{:system, "S3_REGION"}, :instance_role] solved.
Thank you so much!
