### ISSUE TITLE
Deprecation warning for Stream.chunk/4

### ISSUE THREAD

**Issue by fireproofsocks** [ex-aws/ex_aws#626]
This is probably one you're aware of, but...

### Environment

* Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
* Elixir 1.8.1 (compiled with Erlang/OTP 21)
* ExAws version: ex_aws_s3 2.0.1 (Hex package) (mix)
* HTTP client version: hackney 1.15.1 (Hex package) (rebar3)

### Current behavior

Observed during compilation:
```
warning: Stream.chunk/4 is deprecated. Use Stream.chunk_every/4 instead
  lib/ex_aws/s3/delete_all_objects.ex:34
```

### Expected behavior
No deprecation warnings.

**Comment by joneslee85** [comment]
This warning is unrelated to `ex_aws` and was addressed upstream in `ex_aws_s3`, please see https://github.com/ex-aws/ex_aws_s3/blob/master/lib/ex_aws/s3/delete_all_objects.ex#L34

You can close this issue.

**Comment by bernardd** [comment]
Thanks @runlevel5
