### ISSUE TITLE
configparser_ex dependency is out of date

### ISSUE THREAD

**Issue by fireproofsocks** [ex-aws/ex_aws#627]
### Environment

* Elixir & Erlang versions (elixir --version):
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
Elixir 1.8.1 (compiled with Erlang/OTP 21)
```
* ExAws version `mix deps |grep ex_aws`:
```
* ex_aws 2.1.0 (Hex package) (mix)
  locked at 2.1.0 (ex_aws) b9265152
* ex_aws_s3 2.0.1 (Hex package) (mix)
  locked at 2.0.1 (ex_aws_s3) 9e09366e
```
* HTTP client version. IE for hackney do `mix deps | grep hackney`
```
* hackney 1.15.1 (Hex package) (rebar3)
  locked at 1.15.1 (hackney) 9f8f471c
```
### Current behavior
Using `mix hex.outdated` shows that `configparser_ex` has a version 4.0.0, but update is not possible because ex_aws requires version 2.0.

### Expected behavior
Can we bump the versions on this?

**Comment by benwilson512** [comment]
PR welcome.
