### ISSUE TITLE
Documentation example is not up to date

### ISSUE THREAD

**Issue by philipgiuliani** [ex-aws/ex_aws#634]
I tried to switch from `:hackney` to `HTTPotion` using the example in the documentation, but it is not up to date anymore.

> warning: function request/5 required by behaviour ExAws.Request.HttpClient is not implemented (in module VideoTaxi.ExAws.Request.HTTPotion)
  lib/video_taxi/ex_aws/request/httpotion.ex:1

The fifth argument `http_opts` is missing.

https://github.com/ex-aws/ex_aws/blob/c572b2d30e5e56240d5cf429045cc84e9f708bb8/lib/ex_aws/request/http_client.ex#L23

**Comment by JoeARO** [comment]
@philipgiuliani the example in the documentation has been updated, so you can probably close this.
