### ISSUE TITLE
Streaming http response via hackney stream_to causes CaseClauseError

### ISSUE THREAD

**Issue by arnomi** [ex-aws/ex_aws#635]
### Environment

* Elixir & Erlang versions: 1.7.4, 21.1
* ExAws: 2.1.1 
* hackney: 1.15.1

### Current behavior

When using hackney in streaming mode via `http_opts: [stream_to: self, async: :once]` ExAws breaks with a case clause error:

```
iex> %ExAws.Operation.RestQuery{
...>  http_method: :post,
...>  path: "/getMedia",
...>  params: %{},
...>  body: %{
...>    "StreamName" => "XXX",
...>	"StartSelector": %{
...>      "StartSelectorType": "PRODUCER_TIMESTAMP",
...>      "StartTimestamp": 0    },
...>  },
...>  service: :kinesisvideo,
...>} |> ExAws.stream!(region: "eu-west-1", host: "somehost.kinesisvideo.eu-west-1.amazonaws.com",  port: 443, scheme: "https", http_opts: [stream_to: self, async: :once])

** (CaseClauseError) no case clause matching: {:ok, #Reference<0.3549436084.1919942657.159470>}
    lib/ex_aws/request/hackney.ex:21: ExAws.Request.Hackney.request/5
    lib/ex_aws/request.ex:42: ExAws.Request.request_and_retry/7
    lib/ex_aws/operation/rest_query.ex:18: ExAws.Operation.ExAws.Operation.RestQuery.perform/2
```

### Expected behavior

The request not to break and being able to stream responses rather than buffer them up. So probably simply to return `{:ok, ref}` as coming from hackney.  Both `ExAws.Request.Hackney` as well as `ExAws.Request` currently expect a successful result to return `{:ok, %{status_code: status}}`.

The proposal would be to enhance this with the following clause:

```
 {:ok, ref} when is_reference(ref) -> {:ok, ref}
```

**Comment by tpitale** [comment]
This might allow `ex_aws_kinesis` to use SubscribeToShard: https://docs.aws.amazon.com/kinesis/latest/APIReference/API_SubscribeToShard.html

**Comment by benwilson512** [comment]
ExAws doesn't claim this will work. You're welcome to open an issue with a general "how to support HTTP streaming" proposal. Simply returning a ref is implementation specific to hackney.
