### ISSUE TITLE
AWS Rekognition Service

### ISSUE THREAD

**Issue by rageofflames** [ex-aws/ex_aws#636]
Hello,

We are currently working on the AWS Rekognition service and so far we have implemented and launched a package https://github.com/coletiv/ex_aws_rekognition 🎊

We would like to integrate it within the current ex_aws packages to offer yet another service! To do this we are requesting a specific repository like said in the [CONTRIBUTING](https://github.com/ex-aws/ex_aws/blob/master/CONTRIBUTING.md).

Thanks 😄

**Comment by bernardd** [comment]
Hi @rageofflames - I realise it's been a while, but if you're still maintaining the ex_aws_rekognition repo I'm happy to set you up an official one here - let me know.

**Comment by rageofflames** [comment]
Hey @bernardd - yes, we would like to centralise the Rekognition service with the rest 🙌

**Comment by bernardd** [comment]
Done - you should be all set. Thanks!

**Comment by andreragsilva** [comment]
@bernardd can we also give @guilherme1805 push permissions to the repo? 🤔

**Comment by bernardd** [comment]
Hey @andreragsilva - I've added @guilherme1805 and also given you both admin rights so that you can add other people and manage the repo properly yourself (which I should have done originally). Apologies for the delay.
