### ISSUE TITLE
HTTP ERROR: {:closed, ""}

### ISSUE THREAD

**Issue by inderjit23** [ex-aws/ex_aws#641]
i am getting lot of errors in cloudwatch. not able to identify what the issue i.
can anybody please help

`
08:39:20
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:39:20
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 6

08:39:21
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 7

08:39:21
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 8

08:39:23
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 9

08:39:26
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 10

08:39:26
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:39:26
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:39:26
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:39:26
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:39:27
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:39:27
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 6

08:39:27
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 7

08:39:27
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 8

08:39:30
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 9

08:39:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 10

08:39:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 6

08:39:32
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 7

08:39:33
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 8

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 9

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 10

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:39:35
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:40:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:40:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:40:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:40:31
pid=<0.2355.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 6

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 7

08:40:36
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 8

08:40:38
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 9

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 10

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 1

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 2

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 3

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 4

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 5

08:40:40
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 6

08:40:41
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 7

08:40:42
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 8

08:40:43
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 9

08:40:45
pid=<0.2357.0> line=88 function=request_and_retry/7 module=ExAws.Request file=lib/ex_aws/request.ex application=ex_aws [warn] ExAws: HTTP ERROR: {:closed, ""} for URL: "https://logs.eu-west-2.amazonaws.com/" ATTEMPT: 10 `

**Comment by pmenhart** [comment]
The underlying library`ExAws` is using a configurable retry mechanism, default is max. 10 attempts and exponential backoff. You log shows that all request attempts fail with connection closed. Unfortunately, ExAws logging does not provide more details; there could be many possible causes. 

My suggestion is to try reproducing the request with AWS CLI [put-log-events](https://docs.aws.amazon.com/cli/latest/reference/logs/put-log-events.html) from the same machine, using the same AWS authentication mechanism.

**Comment by benwilson512** [comment]
> Unfortunately, ExAws logging does not provide more details;

There aren't really more details in this case. The underlying HTTP library is just teling us that the connection was closed, ExAws doesn't know why either.
