### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by brpandey** [ex-aws/ex_aws#644]
Using the same AWS CLI files, I can run the Amazon CLI and do 
```
aws --profile default cloudwatch list-metrics --namespace "AWS/EC2"
``` 

and I get a full list of results, however, when I use the ExAws version e.g. 
```    
ExAws.Cloudwatch.list_metrics(namespace: "AWS/EC2") |> ExAws.request()
```  

I get 

```
{:error,
 {:http_error, 403,
  %{
    code: "AccessDenied",
    detail: "",
    message: "User: arn:aws:iam::XXXXXX:user/bibek.XXXXX is not authorized to perform: cloudwatch:ListMetrics",
    request_id: "7e227311-a8b3-11e9-bc16-XXXXXXX",
    type: "Sender"
  }}}
```

The ExAws seems like it was able to pull the config properly 

```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role]
```

But did it run assume role properly? What am I missing?

**Comment by benwilson512** [comment]
If your profile is configured to use a role you also need to include `ex_aws_sts` https://github.com/ex-aws/ex_aws_sts#role-based-authentication

**Comment by brpandey** [comment]
Thanks @benwilson512 

Speedy as ever!  

I've tried that and it now errors with: 

```
ExAws.Cloudwatch.list_metrics(namespace: "AWS/EC2") |> ExAws.request()
{:error,
 "Required key: :secret_access_key must be a string, but instead is [{:awscli, \"XXXdev_admin\", 30}]"}
```

The secret_access_key is stored under the ~/.aws/credentials with the default header

[default]
aws_access_key_id = XXXX1
aws_secret_access_key = XXXX2

The ~/.aws/config file is

[default]
region=us-east-1

[profile XXXdev_admin]
region=us-east-1
role_arn=arn:aws:iam::XXXXX:role/XXXXX_Admin
source_profile=default

**Comment by brpandey** [comment]
Here's my new ex_aws config entry

```
config :ex_aws,
  secret_access_key: [{:awscli, "XXXdev_admin", 30}],
  access_key_id: [{:awscli, "XXXXdev_admin", 30}],
  awscli_auth_adapter: ExAws.STS.AuthCache.AssumeRoleCredentialsAdapter

```

**Comment by brpandey** [comment]
Let me know if I am thinking about this correctly --> if my assumptions on how this is supposed to work is right/wrong..

**Comment by benwilson512** [comment]
Testing now

**Comment by benwilson512** [comment]
run `mix deps|grep ex_aws`

**Comment by brpandey** [comment]
* ex_aws 2.0.2 (Hex package) (mix)
  locked at 2.0.2 (ex_aws) 8df2f96f
* ex_aws_sts 2.0.0 (Hex package) (mix)
  locked at 2.0.0 (ex_aws_sts) 0aa9700a
* ex_aws_cloudwatch 2.0.4 (Hex package) (mix)
  locked at 2.0.4 (ex_aws_cloudwatch) f23ac70d

**Comment by benwilson512** [comment]
OK, you should be able to get that config to work if you `mix deps.update ex_aws ex_aws_sts ex_aws_cloudwatch`. That should get you on ExAws 2.1

**Comment by brpandey** [comment]
Fantastic!! It works now.  

You are the man sir @benwilson512
