### ISSUE TITLE
checkout_timeout errors when making dynamodb requests

### ISSUE THREAD

**Issue by Greg-K-GG** [ex-aws/ex_aws#663]
### Environment

* Elixir & Erlang versions: 1.9.2
* ExAws version: 2.1.1
* ExAwsDynamo version: 2.3.1
* HTTP client version: 1.15.2

### Current behavior
I am trying to run a large number of concurrent http requests to dynamo db through EX_AWS.  I am running into `checkout_timeout` errors.   I have checked network bandwidth logs and it doesn't like I am having network lag issues. 

I am not sure if there are any issues making a large number of requests through hackney or ex_aws.  Any advice on how to configure ExAws / Hackney to allow for this would be appreciated.

**Comment by aboroska** [comment]
The bottleneck is the default size (50) of the connection pool hackney uses. ExAws uses HTTPoison which uses hackney under the hood.

See: https://github.com/benoitc/hackney#use-the-default-pool

Using the default pool with default pool size means you cannot have more the 50 concurrent (in-flight) request. When the pool is saturated it sends back `checkout_timeout` after waiting for a configurable time. I think the default is 8s.

The quick workaround is to start a `hackney_pool` with high enough number of workers and modify `:hackney_opts` to use that pool. The pool has to be started early enough, probably part of the application start up. 

`:ok = :hackney_pool.start_pool(:my_pool, max_connections: 200),`


```
config: :ex_aws,
  hackney_opts: [pool: :my_pool]
```

**Comment by Greg-K-GG** [comment]
Thanks @aboroska !

I tried using a pool with a larger connection and it didn't fix my issue.  

I am inspecting the pool stats as I make requests, it looks like I am not coming close to using the entire connection pool when I run into the `:connect_timeout` issues. 
`Pool info: [name: :my_pool, max: 16000, in_use_count: 4609, free_count: 5, queue_count: 0]`

Do you have any other ideas on what could cause this? do you know the syntax to bypass using a pool in that I could use in the `:ex_aws` config?

**Comment by Greg-K-GG** [comment]
Just one more quick update -- I tried using `hackney_opts: [pool: false]` and I still get `:connect_timeout` errors -- not sure if that is the right syntax

**Comment by aboroska** [comment]
`:connect_timeout` is not the pool contention but indicating the refusal to connect by the remote server. The `hackney_pool` related error is the `:checkout_timeout`.

**Comment by aboroska** [comment]
So, if you are getting `:connect_timeout` probably AWS is throttling you. Not sure if this helps:
https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Limits.html#limits-api

**Comment by Greg-K-GG** [comment]
Interesting.. I am using `on demand` mode so it shouldn't be throttled on AWS side. I'll dig into this more.  Thanks again @aboroska !

**Comment by pmenhart** [comment]
If I remember correctly, Dynamo allows max. 50 connections from one IP address. At least that's a limit we experienced few months ago.

**Comment by Greg-K-GG** [comment]
@pmenhart Thanks for the insight!  From the AWS docs it looks like the concurrency limit for updates is indeed 50, but my script is only doing reads.  I think some other part of my script besides the AWS access is causing additional network traffic that may be causing the issues, but I am not certain on that. 

Thanks for all the insight everyone has provided!
