### ISSUE TITLE
Latest code not released on hex.pm

### ISSUE THREAD

**Issue by SteffenDE** [ex-aws/ex_aws#670]
Hey everyone,
I'm running into an issue sending emails from the recently added eu-central-1 region:

```
ses not supported in region eu-central-1 for partition aws
```

This works fine when using the GitHub master branch, as the new regions were recently added. The problem is that the last release on hex.pm is 2.1.1 from May.

It'd be great if you could make a new release with the current code.

**Comment by frm** [comment]
+1, the current version on master is 2.1.2 since #651 but it's stll 2.1.1 on hex

**Comment by benwilson512** [comment]
v2.1.2 is on hex now, thanks for the reminder!
