### ISSUE TITLE
Documentation hidden for `ExAws.Config`

### ISSUE THREAD

**Issue by hoyon** [ex-aws/ex_aws#673]
Hi, I've been trying to use the library with s3 (specifically `ExAws.S3.presigned_url`) and was completely baffled by what the first argument, `config` was. While the documentation there could definitely be improved, it didn't help that the required module (`ExAws.Config`) was completely hidden!

Is there any reason for this since a cursory search through the code and tests show that this is the correct way to create the required config?

It is explicitly disabled here:
https://github.com/ex-aws/ex_aws/blob/7843167836f6ee291241073be21118314e554533/lib/ex_aws/config.ex#L2

**Comment by benwilson512** [comment]
Hi @hoyon I believe this is an oversight on our part, we should definitely remove `@moduledoc false` and add proper documentation.

**Comment by benwilson512** [comment]
PR welcome.
