### ISSUE TITLE
Documentation link to source is broken

### ISSUE THREAD

**Issue by cdvv7788** [ex-aws/ex_aws#676]
# Current behavior

When going to the documentation (https://hexdocs.pm/ex_aws/ExAws.html), there is an icon at the top right:
![image](https://user-images.githubusercontent.com/5531776/74573307-72c86300-4f4e-11ea-8c68-0ea181830486.png)
Clicking it, for example in the homepage, redirects to [](https://github.com/ex-aws/ex_aws/blob/v2.1.1/lib/ex_aws.ex#L1), which is broken. If I change it to [](https://github.com/ex-aws/ex_aws/blob/v2.1.0/lib/ex_aws.ex#L1) it works.

### Expected behavior
The link to source works as expected.

**Comment by benwilson512** [comment]
Fixed on v2.1.2
