### ISSUE TITLE
Changelog is missing latest two releases

### ISSUE THREAD

**Issue by doughsay** [ex-aws/ex_aws#680]
I can't (easily) tell what changed or if there are breaking changes in 2.1.1 and 2.1.2 because they are not mentioned in the changelog.

**Comment by doughsay** [comment]
Again, a new version was released with no changelog visible anywhere.

**Comment by benwilson512** [comment]
Apologies, the commit was made but not pushed. https://github.com/ex-aws/ex_aws/commit/b977551add79c771d738503ff83465fae0e59333

ExAws follows semver. 2.1.X releases will never be breaking.
