### ISSUE TITLE
AWS EKS IAM roles for service accounts support

### ISSUE THREAD

**Issue by jwilf** [ex-aws/ex_aws#683]
### Problem

We are running Elixir in EKS (AWS kubernetes) and need to use S3. Currently we need to pass in AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY via secrets, which presents an administration overhead and possible security issue.

### Solution

I'd like to request that ex_aws supports authentication using [IAM Roles for Service Accounts](https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html).

Using this solution a k8s service account is associated with an IAM role. The SDK should then use the env vars AWS_ROLE_ARN and AWS_WEB_IDENTITY_TOKEN_FILE to authenticate as described in the docs - https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html

Thanks.

**Comment by ajmath** [comment]
I was able to get it working using ex_aws_sts following the guidance on [this section of the docs.](https://github.com/ex-aws/ex_aws_sts/#using-web-identity-tokens-from-env-vars). At the time of writing [this PR](https://github.com/ex-aws/ex_aws_sts/pull/15) has not yet been published to hex so I had to add it using a github sha reference.

The profile that you are referencing the config block doesn't really matter from what I can tell and is only present to align with the existing conventions that come with using `awscli_auth_adapter`

**Comment by shteou** [comment]
> I was able to get it working using ex_aws_sts following the guidance on [this section of the docs.](https://github.com/ex-aws/ex_aws_sts/#using-web-identity-tokens-from-env-vars). At the time of writing [this PR](https://github.com/ex-aws/ex_aws_sts/pull/15) has not yet been published to hex so I had to add it using a github sha reference.
> 
> The profile that you are referencing the config block doesn't really matter from what I can tell and is only present to align with the existing conventions that come with using `awscli_auth_adapter`

Thanks @ajmath! I'm replying on behalf of James here, I think that makes sense. We'll see how we get on with `ex_aws_sts`.

**Comment by shteou** [comment]
FYI, have confirmed this works (with 2.1.0 of ex_aws_sts), thanks again @ajmath .
@jwilf I think this can be closed 👍

**Comment by RobinFrcd** [comment]
Hi all ! How did you configure it ?

I tried:
```
config :ex_aws,
  access_key_id: [{:system, "AWS_ACCESS_KEY_ID"}, {:awscli, "default", 30}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, {:awscli, "default", 30}, :instance_role],
  region: [{:system, "AWS_REGION"}, {:awscli, "default", 30}, :instance_role],
  awscli_auth_adapter: ExAws.STS.AuthCache.AssumeRoleCredentialsAdapter
```

but it didn't work
