### ISSUE TITLE
ExAws will resolve to old version because of jason version restriction

### ISSUE THREAD

**Issue by achempion** [ex-aws/ex_aws#686]
### Environment

* Elixir 1.9.4
* ExAws 2.1.2
* hackney not installed

### Current behavior

ExAws 2.1.1 will be installed.

### Expected behavior

ExAws 2.1.2 will be installed.

### How to reproduce

```sh
$ mix new test
```
add dependencies to mix.exs
```elixir
  defp deps do
    [
      {:jason, "~> 1.0"},
      {:ex_aws, "~> 2.1"}
    ]
  end
```

```sh
$ mix deps.get

Resolving Hex dependencies...
Dependency resolution completed:
New:
  ex_aws 2.1.1
  jason 1.2.0
* Getting jason (Hex package)
* Getting ex_aws (Hex package)
```

The issue here is `2.1.2` introduces the [version restriction](https://diff.hex.pm/diff/ex_aws/2.1.1..2.1.2#84732810--38) for `jason` library but `2.1.1` don't have this restriction.

Can we remove restriction for `jason` in order to get the latest version? Because `2.1.1` contains bug with `+` symbol escaping to space.

Relates to https://github.com/elixir-waffle/waffle/pull/32.

**Comment by benwilson512** [comment]
The restriction has been lowered in master, I'll cut a new release.

**Comment by benwilson512** [comment]
Oh, Jason is all the way on version 2 now. Will relax further.

**Comment by benwilson512** [comment]
Release pushed, thanks!
