### ISSUE TITLE
ExAws.Auth.remove_dup_spaces runs hot during load testing

### ISSUE THREAD

**Issue by Shayon** [ex-aws/ex_aws#693]
### Environment

* Elixir & Erlang versions: `Elixir 1.10.2 (compiled with Erlang/OTP 22)`
* ExAws version: `ex_aws 2.1.3`
* ExAwsDynamo version: `ex_aws_dynamo 3.0.1`
* HTTP client version: `hackney 1.15.2`

### Problem

We are writing a simple phoenix application that provides an API to query a DynamoDB Table.  during early stages of load testing this service we noticed high process memory usage and high system load on our host at just 500 req/s (each request makes one query to the Dynamo Table).  We used [`:fprof`](https://erlang.org/doc/man/fprof.html) to look deeper and found that the function with the highest call count by a factor of 5 (to the third highest call count) was `ExAws.Auth.remove_dup_spaces` and the function with the second highest call count by a factor of 2 (to the third highest call count) was `Jason.Decoder.string` being called by `Jason.Decoder.parse`.

Is this relatively high call rate expected?  If so, is there something we can do to alter the code in question to optimize performance of the library? Alternatively is there something we, as consumers of this library, can do to optimize our implementation for high request loads?

**Comment by benwilson512** [comment]
Hi @Shayon. Definitely an interesting problem. I'd highly recommend posting on the ElixirForum or other community resources. I do not have time to provide this kind of analysis on these libraries these days. I'll leave the issue open in case someone else sees it and is willing to weigh in however.

**Comment by Shayon** [comment]
I am sharing my journey towards better performance on the [Elixir forum](https://elixirforum.com/t/help-optimizing-or-profiling-performace-of-ex-aws-hackney/31625/6).
