### ISSUE TITLE
Release code in master

### ISSUE THREAD

**Issue by tomaspinho** [ex-aws/ex_aws#706]
We're asking for a release of the code currently in master, we've spent a few hours debugging the issue fixed by https://github.com/ex-aws/ex_aws/commit/42521e7a4f07204d4cd455e43e075d69de2078d1 as a team only to find that it had already been fixed in master and not the latest version in hexpm, which we were using.

**Comment by ylebedeva** [comment]
Our team needs this fix as well for an app in production. Would it be possible to release a patched version in the near future?

**Comment by tomaspinho** [comment]
Looks like @benwilson512 just released it!
