### ISSUE TITLE
Requesting repo for ex_aws_acm

### ISSUE THREAD

**Issue by anthonator** [ex-aws/ex_aws#708]
I put together ACM support for ExAws and would like to request a repo.

https://github.com/malomohq/ex_aws_acm

I'm happy to maintain this project.

**Comment by benwilson512** [comment]
https://github.com/ex-aws/ex_aws#deprecation-notice

**Comment by bernardd** [comment]
Hi @anthonator - I've set up the repo for you: https://github.com/ex-aws/ex_aws_acm/
Have fun, and thanks!
