### ISSUE TITLE
Could not find how to add security token (AWS Session Token) in the documentation

### ISSUE THREAD

**Issue by sulabh-kothari** [ex-aws/ex_aws#709]
* Elixir  1.10.4 
* ExAws version 2.1.4

The README file does not tell how to set the AWS session token. Our call was continuously failing to connect with AWS with the 2 parameters set (`access_key_id` and `secret_access_key`). These are the only 2 parameters described in the readme documentation. We had to figure out from the source code that aws session token can be set as `security_token`. It will be better if this is also added to the readme doc file. 
We also asked this question  in the Elixir forum https://elixirforum.com/t/unable-to-configure-ex-aws-for-sqs/33795 and updated with the answer.
You can reach out to me for more details around it at sulabh.kothari@deserve.com.

**Comment by Nitrodist** [comment]
@sulabhk-deserve same

**Comment by benwilson512** [comment]
https://github.com/ex-aws/ex_aws#deprecation-notice

**Comment by bernardd** [comment]
I'm more than happy for this to be added to the docs if someone would be kind enough to sumit a PR.
