### ISSUE TITLE
Add a logo for this repository

### ISSUE THREAD

**Issue by MattLongCode** [ex-aws/ex_aws#713]
### Current behavior

No logo.

### Expected behavior

Add a logo.

### Reason

It could look better.

**Comment by MattLongCode** [comment]
![image](https://user-images.githubusercontent.com/6936706/94127221-917dc900-fe50-11ea-9cb2-20298b50271d.png)

**Comment by benwilson512** [comment]
Hi Matt, there are no plans to add a logo, thanks.
