### ISSUE TITLE
Requesting repo for ex_aws_timestream

### ISSUE THREAD

**Issue by mike-foucault** [ex-aws/ex_aws#714]
Hi,

Amazon Timestream database is now generally available.

I wrote an ex_aws_timestream service module and I would like it to be shared under github.com/ex-aws.
https://github.com/mike-foucault/ex_aws_timestream
https://hex.pm/packages?search=ex_aws_timestream&sort=recent_downloads

Example (in region eu-west-1): 

```elixir
ExAws.Timestream.describe_write_endpoints
|> ExAws.request(region: "eu-west-1")
```

Response:

```elixir
{:ok,
 %{
   "Endpoints" => [
     %{
       "Address" => "ingest-cell1.timestream.eu-west-1.amazonaws.com",
       "CachePeriodInMinutes" => 1440
     }
   ]
 }}
```

All API actions are wrapped (https://docs.aws.amazon.com/timestream/latest/developerguide/API_Operations.html)

To directly access the REST APIs, we must use the Endpoint Discovery Pattern, so currently (version "0.1.0" of the hex package), we must use an endpoint as host to make a valid request.

Example (in region eu-west-1): 

```elixir
host = "ingest-cell1.timestream.eu-west-1.amazonaws.com"
ExAws.Timestream.create_database("github_demo")
|> ExAws.request(region: "eu-west-1", host: host)
```

Response : 

```elixir
{:ok, 
 %{  
   "Database" => %{. 
     "Arn" => ...,  
     "CreationTime" => 1601940687.325,  
     "DatabaseName" => "github_demo",  
     "KmsKeyId" => ...,  
     "LastUpdatedTime" => 1601940687.325,  
     "TableCount" => 0. 
   }. 
 }}
```

Notes :

- I'm working on a solution to hide all "endpoint logics" but the current version can be used.
- I will publish another issue/PR to add the right service configuration to ExAws endpoint file.

**Comment by benwilson512** [comment]
https://github.com/ex-aws/ex_aws#deprecation-notice

**Comment by bernardd** [comment]
Hi @mike-foucault - I've set you up a repo at https://github.com/ex-aws/ex_aws_timestream
Thanks and have fune!
