### ISSUE TITLE
Support for af-south-1

### ISSUE THREAD

**Issue by Ivor** [ex-aws/ex_aws#727]
Currently the new region: `af-south-1` for Cape Town in South Africa is not added in the [endpoints.exs](https://github.com/ex-aws/ex_aws/blob/master/priv/endpoints.exs) file. 

I'm not sure how that file is structured. 
As an example of what I am trying to do: 
I have instances in Paris and Cape Town. 
If I list the Paris instances with ExAws.ExAws.Ec2:

````
%ExAws.Operation.Query{
  action: :describe_instances,
  content_encoding: "identity",
  params: %{"Action" => "DescribeInstances", "Version" => "2016-11-15"},
  parser: &ExAws.Utils.identity/2,
  path: "/",
  service: :ec2
}
```

I get the list of instances back. 
When I do the same for Cape Town (af-south-1) I get an error back that looks like the response below: 

```
[warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/" ATTEMPT: 1
[warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/" ATTEMPT: 2
[warn] ExAws: HTTP ERROR: :nxdomain for URL: "https:/" ATTEMPT: 3
```

**Comment by bernardd** [comment]
`af-south-1` is now in the endpoints file.
