### ISSUE TITLE
Support for eu-south-1 region missing for S3 service

### ISSUE THREAD

**Issue by annienencheva** [ex-aws/ex_aws#730]
### Environment

* Elixir & Erlang versions: Elixir 1.11.0 (compiled with Erlang/OTP 23)
* ExAws version:  ex_aws 2.1.6, ex_aws_s3 2.1.0
* HTTP client version: hackney 1.16.0

### Current behavior
Seems like buckets located in the eu-south-1 region can't be used. 
```
iex(1)> ExAws.Config.Defaults.get("s3", "eu-south-1")
** (RuntimeError) s3 not supported in region eu-south-1 for partition aws
    (ex_aws 2.1.6) lib/ex_aws/config/defaults.ex:156: ExAws.Config.Defaults.fetch_or/3
    (ex_aws 2.1.6) lib/ex_aws/config/defaults.ex:139: ExAws.Config.Defaults.do_host/3
    (ex_aws 2.1.6) lib/ex_aws/config/defaults.ex:76: ExAws.Config.Defaults.get/2
```

Would adding `"eu-south-1" => %{}` [here](https://github.com/ex-aws/ex_aws/blob/master/priv/endpoints.exs#L1263) be enough?

**Comment by bernardd** [comment]
Should be, yeah. Assuming it works for you it'd be great to get a PR. Cheers.
