### ISSUE TITLE
Incorrect spec on ExAws.Request.HttpClient ?

### ISSUE THREAD

**Issue by sparkertime** [ex-aws/ex_aws#743]
There's a mismatch between the behavior `ExAws.Request.HttpClient` and the parameters returned by its implementation `ExAws.Request.Hackney`.

The behavior is typed as returning

```
{:ok, %{status_code: pos_integer, body: binary}}
| {:error, %{reason: any}}
```

`ExAws.Request.Hackney` returns an additional `headers` key like roughly so

```
{:ok, %{status_code: pos_integer, headers: any}}
| {:ok, %{status_code: pos_integer, body: binary, headers: any}}
| {:error, %{reason: any}}
```

This only matters because ex_aws_s3 requires the headers to be present even though they aren't in the behavior's specification. Writing a new `HttpClient` implementation explodes for S3 unless you include the headers

**Comment by bernardd** [comment]
Good catch, thanks. I've updated the spec in #750
