### ISSUE TITLE
Creating an S3 "folder" fails

### ISSUE THREAD

**Issue by mbklein** [ex-aws/ex_aws#752]
### Environment

* Elixir & Erlang versions (elixir --version):
    ```
    Erlang/OTP 23 [erts-11.1.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]
    
    Elixir 1.11.1 (compiled with Erlang/OTP 23)
    ```
* ExAws version `2.1.7`
* HTTP client version: `hackney 1.17.0`

### Current behavior

With `ExAws` 2.1.6 and earlier, it was possible to create a pseudo-folder in S3 by calling:
```
ExAws.S3.put_object("my-bucket", "folder-name/", "")
|> ExAws.request()
```
The trailing slash was the key to making it appear as a folder and not a zero-byte binary object in the parent folder.

Starting with `ExAws` 2.1.7, the trailing slash gets stripped from the key name, which causes the undesirable result.

### Expected behavior

`ExAws.Operation.S3` does not strip trailing `/` characters from key names

**Comment by bernardd** [comment]
Thanks @mbklein - good catch. I've pushed a fix for this: #753
