### ISSUE TITLE
Support for sa-east-1 on cognito-idp

### ISSUE THREAD

**Issue by DouglasLutz** [ex-aws/ex_aws#779]
AWS recently added cognito service on south america region. 

https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-cognito-is-now-available-in-the-south-america-and-us-west-regions/

Would be nice to have support for sa-east-1 on cognito-idp service, in case of acceptance I would gladly open a PR for this issue.

**Comment by bernardd** [comment]
No problem at all with adding it if you'd be kind enough to PR it.
