### ISSUE TITLE
:telemetry.span/3 is undefined or private

### ISSUE THREAD

**Issue by sescobb27** [ex-aws/ex_aws#794]
### Environment

* Elixir & Erlang versions (elixir --version): 1.11.3
* ExAws version: 2.2.3

### Current behavior

hi @bernardd just upgrade to latest version of ExAws but now i'm getting

Change introduced here https://github.com/ex-aws/ex_aws/pull/785

```
** (UndefinedFunctionError) function :telemetry.span/3 is undefined or private
```

### Expected behavior

to have telemetry as optional dependency or to not get undefined function

**Comment by bernardd** [comment]
Dang, thanks @sescobb27 . Turns out the specified version of telemetry was a bit loose and allowed earlier minor versions that didn't include the function. I've fixed it up.
