### ISSUE TITLE
Support SESSION_TOKEN to authenticate

### ISSUE THREAD

**Issue by benkeil** [ex-aws/ex_aws#802]
It would be nice to have more login options in order to work with assume role or awsume.

**Comment by trbngr** [comment]
this already works for me in a lambda.

```
config :ex_aws,
  access_key_id: {:system, "AWS_ACCESS_KEY_ID"},
  security_token: {:system, "AWS_SESSION_TOKEN"},
  secret_access_key: {:system, "AWS_SECRET_ACCESS_KEY"}
```

**Comment by benkeil** [comment]
Ok, it works. Then we should just add it to the documentation. And maybe we could rename security_token to session_token to be more conform with the aws api.

**Comment by bernardd** [comment]
If you're able to do a PR to add it to the docs that would be awesome.

**Comment by benkeil** [comment]
It would be a breaking change, how to deal with it? add a new parameter and deprecate the old one?

**Comment by bernardd** [comment]
No, I just meant a PR to add it to the docs. We could make both names work, sure, but the feature already exists so I don't see huge value in doing that.
