### ISSUE TITLE
v2.2.4 returns InvalidAccessKeyId on S3 calls from EC2 with instance role

### ISSUE THREAD

**Issue by ZombieHarvester** [ex-aws/ex_aws#814]
Elixir: 1.12.1 compiled with Erlang/OTP 24
ex_aws: 2.2.4
ex_aws_s3: 2.3.0
hackney: 1.17.4

### Current behavior
```Elixir
bucket_name
|> S3.put_object(filename, file)
|> ExAws.request!
```
raises

```Elixir
ExAws.Error: ExAws Request Error!

{:error,
 {:http_error, 403,
  %{
    body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>...</AWSAccessKeyId><RequestId>...</RequestId><HostId>...</HostId></Error>",
    headers: [
      {"x-amz-bucket-region", "ap-southeast-1"},
      {"x-amz-request-id", "..."},
      {"x-amz-id-2", "..."},
      {"Content-Type", "application/xml"},
      {"Transfer-Encoding", "chunked"},
      {"Date", "Thu, 02 Sep 2021 14:39:11 GMT"},
      {"Server", "AmazonS3"}
    ],
    status_code: 403
  }}}

File "lib/ex_aws.ex", line 87, in ExAws.request!/2
```

### Config

```Elixir
config :ex_aws,
  access_key_id:     [{:system, "AWS_ACCESS_KEY_ID"}, :instance_role],
  secret_access_key: [{:system, "AWS_SECRET_ACCESS_KEY"}, :instance_role],
  region:            System.get_env("AWS_REGION")
```

Uses instance role auth on EC2, access key is not set in env

### Expected behavior

Same as in v2.2.3: file is uploaded, status_code 200 returned.

### Comment

Locally it works fine with access key auth on both v2.2.3 and v2.2.4.  On EC2 with instance role auth v.2.2.4 raises

**Comment by bernardd** [comment]
Oops, interesting. My guess is that it's most likely to do with #796, though it's not immediately obvious how. I'll take a look at it as soon as I can.

**Comment by wkirschbaum** [comment]
We are getting %{code: "InvalidClientTokenId", message: "The security token included in the request is invalid."} for ExAws.SES.send_email on AWS ECS after upgrading to 2.2.4, but it works as expected on 2.2.3

**Comment by bernardd** [comment]
@ZombieHarvester @wkirschbaum If you're able to, could you try out the code on the `config_fixes` branch please? I ended up having to rework the config loading system to be able to fix both this bug and #796, and while it passes all the tests plus the new ones I added, I'd love for you guys to try it out before I do another release. Cheers.

**Comment by wkirschbaum** [comment]
@bernardd thanks for checking. yes, i will have a look over the weekend.

**Comment by ZombieHarvester** [comment]
@bernardd I have tried, same result as on 2.2.4

My steps to reproduce:

### v.2.2.3

```Elixir
$ iex

> Mix.install([{:ex_aws, "2.2.3"}, {:ex_aws_s3, "~> 2.0"}, {:hackney, "~> 1.9"}, {:sweet_xml, "~> 0.6"}, {:jason, "~> 1.2"}])

> ExAws.S3.list_buckets |> ExAws.request

{:ok,
 %{
   body: %{
     buckets: [...]}, 
     headers: [...]}, 
     status_code: 200
  }
}
```  

### config_fixes branch or 2.2.4

```Elixir
$ iex

> Mix.install([{:ex_aws, github: "ex-aws/ex_aws", branch: "config_fixes", override: true}, {:ex_aws_s3, "~> 2.0"}, {:hackney, "~> 1.9"}, {:sweet_xml, "~> 0.6"}, {:jason, "~> 1.2"}])

> ExAws.S3.list_buckets |> ExAws.request

{:error,
 {:http_error, 403,
  %{
    body: "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Error><Code>InvalidAccessKeyId</Code><Message>The AWS Access Key Id you provided does not exist in our records.</Message><AWSAccessKeyId>...</AWSAccessKeyId><RequestId>...</RequestId><HostId>...</HostId></Error>",
    headers: [...],
    status_code: 403
  }}}
```

I have noticed that on 2.2.4 and config_fixes config security_token is missing. Maybe that is the reason?

###  2.2.3 config

```Elixir
> ExAws.Config.new(:s3) 
%{
  access_key_id: "...",
  host: "s3.amazonaws.com",
  http_client: ExAws.Request.Hackney,
  json_codec: Jason,
  normalize_path: true,
  port: 443,
  region: "us-east-1",
  retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000],
  scheme: "https://",
  secret_access_key: "...",
  security_token: "..." # <- missing in 2.2.4 and config_fixes
}
```

###  2.2.4 config

```Elixir
> ExAws.Config.new(:s3) 
%{
  access_key_id: "...",
  host: "s3.amazonaws.com",
  http_client: ExAws.Request.Hackney,
  json_codec: Jason,
  normalize_path: true,
  port: 443,
  region: "us-east-1",
  retries: [max_attempts: 10, base_backoff_in_ms: 10, max_backoff_in_ms: 10000],
  scheme: "https://",
  secret_access_key: "..."
}
```

**Comment by bernardd** [comment]
Ah, thanks @ZombieHarvester - I see the issue now. Now I just have to figure out how to fix it.

**Comment by bernardd** [comment]
Okay, having spelt on it, what I'm going to to is just revert the change that caused the breakage, and figure out a more comprehensive solution for a minor release (since it will inevitably involve changing some behaviour. And it's a safe bet that no matter how obscure the behaviour is, *someone* is going to be relying on it.

Thanks for the report and the help tracking it down.
