### ISSUE TITLE
No git tag for v2.2.7

### ISSUE THREAD

**Issue by ericfreese** [ex-aws/ex_aws#837]
It looks like a git tag was never created for v2.2.7. It'd be nice to get this in so that code links from hexdocs resolve correctly. As it is now, if you click the code icon to the right of a heading here (https://hexdocs.pm/ex_aws/ExAws.html) you get a 404 like https://github.com/ex-aws/ex_aws/blob/v2.2.7/lib/ex_aws.ex#L1

**Comment by bernardd** [comment]
Thanks for the reminder @ericfreese - I've added a tag.
