### ISSUE TITLE
ex_aws_sns project - maintenance

### ISSUE THREAD

**Issue by brunozrk** [ex-aws/ex_aws#841]
Sorry if this is not the right place to ask (but is about contribution 😄 ), but is the project https://github.com/ex-aws/ex_aws_sns/ still maintained?

I opened a PR (https://github.com/ex-aws/ex_aws_sns/pull/19) there but I realized that there are very old ones without response

**Comment by bernardd** [comment]
Hi @brunozrk - the answer is "not actively by me" :) I kind of inherited ex_aws last year and I'm still figuring out who, if anyone, looks after all the different sub-packages. I do, however, have write access on all of them so I'll try to take a look at your patch and the others this coming weekend.

**Comment by brunozrk** [comment]
Oh, Thanks @bernardd
