### ISSUE TITLE
Support for me-south-1 for cloud watch logs and cloud watch metrics

### ISSUE THREAD

**Issue by avivek** [ex-aws/ex_aws#844]
I am using the library https://github.com/noxdafox/rabbitmq-cloudwatch-exporter which internally uses this library for the AWS functions.
We have deployed in the me-south-1(Bahrain region).
The me-south-1 region supports cloudwatch metrics and also cloud watch logs but the library needs to be updated for the same.

I am thinking that the changes are minor and would require changes in the below sections:
https://github.com/ex-aws/ex_aws/blob/main/priv/endpoints.exs#L12

https://github.com/ex-aws/ex_aws/blob/main/priv/endpoints.exs#L614
and
https://github.com/ex-aws/ex_aws/blob/main/priv/endpoints.exs#L291

Is this fine??

**Comment by avivek** [comment]
@bernardd Raised the following PR for the same.
Please review
https://github.com/ex-aws/ex_aws/pull/845

**Comment by avivek** [comment]
@bernardd how do we get this on a release so that the dependent library can update its dependencies.

**Comment by bernardd** [comment]
You ask nicely then wait until I have a spare moment :)
