### ISSUE TITLE
Please include the "x-amz-target" header value in telemetry events

### ISSUE THREAD

**Issue by juancgalvis** [ex-aws/ex_aws#930]
### Environment

* Elixir & Erlang versions `elixir --version`: 1.13.4
* ExAws version `mix deps | grep ex_aws`: 2.4.1
* HTTP client version. IE for hackney do `mix deps | grep hackney`: 1.18.1

### Current behavior

The current events have only the AWS service name in metadata.

```elixir
%{
  attempt: 1,
  options: [],
  result: :ok,
  service: :secretsmanager,
  telemetry_span_context: #Reference<0.3450093779.1724645383.45512>
}
```
### Expected behavior

Would be great to include the operation that is being executed. For example:

```elixir
%{
  attempt: 1,
  options: [],
  result: :ok,
  service: :secretsmanager,
  operation: "secretsmanager.GetSecretValue"
  telemetry_span_context: #Reference<0.3450093779.1724645383.45512>
}
```

I will be able to contribute if you appreciate this functionality.

**Comment by bernardd** [comment]
Ha - I've got to be honest, I only just now learned that ex_aws even emits telemetry events :) Yes, I'm quite happy to have extra information like the operation added to them - please feel free to submit a PR!
