### ISSUE TITLE
Compatibility with other providers?

### ISSUE THREAD

**Issue by mvkvc** [ex-aws/ex_aws#938]
Hello,

I would like to use this library to upload to Backblaze B2, which is an S3 compatible store with has an endpoint like `s3.us-west-002.backblazeb2.com`. Is this possible?

Thank you

**Comment by bernardd** [comment]
Yep, in general you should just be able to set the `host` value in the config to override it to whatever the hostname you want is.

**Comment by mvkvc** [comment]
Thank you!

**Comment by ndrean** [comment]
Hi. How do you set the `host` ?

**Comment by peaceful-james** [comment]
> Hi. Thanks, indeed, just "host" and "client_id" and "client_secret" for B2.
> 
> ```elixir
> config :ex_aws, :s3,
>    host: "https://s3.eu-central-003.backblazeb2.com/<my-bucket>
>    region: eu-central-003,
>    ...
> ```

This will not work. When you specify the region like this in the config, you will get an error like

> s3 not supported in region eu-central-003 for partition aws

Just do not specify the region.

See here: https://elixirforum.com/t/backblaze-and-ex-aws-ex-aws-s3-2-4-3-presign-url-issue/56805
