### ISSUE TITLE
2.4.3 release?

### ISSUE THREAD

**Issue by mthiemsAtCorvus** [ex-aws/ex_aws#956]
[hex.pm is showing a 2.4.3 release](https://hex.pm/packages/ex_aws/2.4.3), but it doesn't appear here on GitHub. There doesn't appear to be any commit bumping the version in mix.exs, nothing in CHANGELOG.md, no tag, etc.

[hexdocs.pm is also showing a 2.4.3](https://hexdocs.pm/ex_aws/2.4.3/readme.html), but the [source links from there](https://github.com/ex-aws/ex_aws/blob/v2.4.3/README.md#L1) result in a 404 on GitHub.

**Comment by bernardd** [comment]
Whoops, got distracted and forgot to push stuff - thanks for the reminder :)
