### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by isavita** [ex-aws/ex_aws#979]
My application is using ExAws for Lambda call with relatively large body in the response (400KB gzip) responses from aws lambda. I notice that in the request [module ExAws.Request](https://github.com/ex-aws/ex_aws/blob/main/lib/ex_aws/request.ex#L1) there is some copying of the response_body in for telemetry stats [here](https://github.com/ex-aws/ex_aws/blob/main/lib/ex_aws/request.ex#L121).
Is there any way to avoid this (e.g. config)?

### Environment

* Elixir & Erlang versions (elixir --version): `Elixir 1.14.3 (compiled with Erlang/OTP 23)`
* ExAws version: `ex_aws 2.4.4`
* HTTP client version:  `finch 0.13.0`

### Current behavior
There is some copying the response body for :telemetry that increase the memory usage [here](https://github.com/ex-aws/ex_aws/blob/main/lib/ex_aws/request.ex#L121).

### Expected behavior
I would expect to be able to disable this copy of the response body to telemetry or in general to be able to disable telemetry.

**Comment by bernardd** [comment]
I'm not quite clear how you come to the conclusion that that line causes a copy of the body (not saying it's not, just that I don't understand). Telemetry operations all occur in-process, so unless the body is modified I don't see any reason to imaging it's being copied there.

**Comment by isavita** [comment]
You mean the copy is for the result in the :telemetry.span as a whole. Is there way to remove this :telemetry.span wrapper or disable it?

**Comment by bernardd** [comment]
To the best of my understanding, step 4 should not create a copy of the body - it should just add a reference to the existing binary. How are you measuring memory use? It would be interesting to know exactly what aspect of memory use is increasing (using `:erlang.memory()` will show you the breakdown) - I think the body would be part of `binary` so you'd expect to see that jump up at that point if it's really being copied.

**Comment by isavita** [comment]
@bernardd I've investigated more closely but cannot reproduce the issue. I am closing it.
